-- Legacy certificate tables remain isolated for retention; no active routes use them.
CREATE TABLE projects (id TEXT PRIMARY KEY, name TEXT NOT NULL, client_name TEXT NOT NULL DEFAULT '', owner_id TEXT NOT NULL REFERENCES users(id), start_date TEXT, end_date TEXT, created_at TEXT NOT NULL, CHECK(end_date IS NULL OR start_date IS NULL OR end_date >= start_date));
CREATE INDEX projects_owner ON projects(owner_id,created_at);
CREATE TABLE creators (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), name TEXT NOT NULL, email TEXT NOT NULL DEFAULT '', role TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(id,project_id));
CREATE TABLE assets (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), creator_id TEXT, filename TEXT NOT NULL, mime_type TEXT NOT NULL, size INTEGER NOT NULL CHECK(size >= 0), created_at TEXT NOT NULL, FOREIGN KEY(creator_id,project_id) REFERENCES creators(id,project_id));
CREATE INDEX assets_project ON assets(project_id,created_at);
CREATE TABLE asset_versions (id TEXT PRIMARY KEY, asset_id TEXT NOT NULL REFERENCES assets(id), version INTEGER NOT NULL CHECK(version > 0), sha256 TEXT NOT NULL CHECK(length(sha256)=64 AND sha256 NOT GLOB '*[^0-9a-f]*'), status TEXT NOT NULL CHECK(status IN ('DRAFT','SUBMITTED','APPROVED','FINAL')), comment TEXT NOT NULL DEFAULT '', created_by TEXT NOT NULL REFERENCES users(id), creator_id TEXT REFERENCES creators(id), filename TEXT NOT NULL, mime_type TEXT NOT NULL, size INTEGER NOT NULL CHECK(size >= 0), created_at TEXT NOT NULL, UNIQUE(asset_id,version));
CREATE TABLE proofs (id TEXT PRIMARY KEY, asset_version_id TEXT NOT NULL UNIQUE REFERENCES asset_versions(id), sha256 TEXT NOT NULL, timestamp_status TEXT NOT NULL DEFAULT 'NOT_REQUESTED' CHECK(timestamp_status IN ('NOT_REQUESTED','PENDING','CONFIRMED','FAILED')), ots_proof BLOB, bitcoin_status TEXT NOT NULL DEFAULT 'NOT_REQUESTED' CHECK(bitcoin_status IN ('NOT_REQUESTED','PENDING','CONFIRMED','FAILED')), timestamp TEXT, created_at TEXT NOT NULL);
CREATE TABLE approvals (id TEXT PRIMARY KEY, asset_version_id TEXT NOT NULL REFERENCES asset_versions(id), approver_id TEXT NOT NULL REFERENCES users(id), status TEXT NOT NULL CHECK(status IN ('APPROVED','REJECTED')), comment TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL);
CREATE TRIGGER version_no_update BEFORE UPDATE ON asset_versions BEGIN SELECT RAISE(ABORT,'version history is immutable'); END;
CREATE TRIGGER version_no_delete BEFORE DELETE ON asset_versions BEGIN SELECT RAISE(ABORT,'version history is permanent'); END;
CREATE TRIGGER creator_proof_no_delete BEFORE DELETE ON proofs BEGIN SELECT RAISE(ABORT,'proof history is permanent'); END;
CREATE TRIGGER creator_proof_hash_immutable BEFORE UPDATE OF sha256,asset_version_id,created_at ON proofs BEGIN SELECT RAISE(ABORT,'proof identity is immutable'); END;
CREATE TRIGGER creator_proof_hash_matches BEFORE INSERT ON proofs WHEN NOT EXISTS(SELECT 1 FROM asset_versions WHERE id=NEW.asset_version_id AND sha256=NEW.sha256) BEGIN SELECT RAISE(ABORT,'proof hash mismatch'); END;
