ALTER TABLE projects ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN archived_at TEXT;
ALTER TABLE projects ADD COLUMN is_demo INTEGER NOT NULL DEFAULT 0;
ALTER TABLE assets ADD COLUMN archived_at TEXT;
ALTER TABLE assets ADD COLUMN created_by TEXT REFERENCES users(id);
ALTER TABLE assets ADD COLUMN external_source_url TEXT;
ALTER TABLE assets ADD COLUMN is_demo INTEGER NOT NULL DEFAULT 0;
ALTER TABLE proofs ADD COLUMN proof_status TEXT NOT NULL DEFAULT 'PENDING' CHECK(proof_status IN ('PENDING','STAMPED','WAITING_BITCOIN','CONFIRMED','FAILED'));
ALTER TABLE proofs ADD COLUMN timestamp_created_at TEXT;
ALTER TABLE proofs ADD COLUMN bitcoin_confirmed_at TEXT;
ALTER TABLE proofs ADD COLUMN bitcoin_block INTEGER;
ALTER TABLE proofs ADD COLUMN retry_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE proofs ADD COLUMN last_retry_at TEXT;
ALTER TABLE proofs ADD COLUMN error_code TEXT;
ALTER TABLE proofs ADD COLUMN error_message TEXT;
ALTER TABLE proofs ADD COLUMN updated_at TEXT;
ALTER TABLE proofs ADD COLUMN lease_until TEXT;
CREATE INDEX proofs_pending ON proofs(proof_status,last_retry_at);
CREATE TABLE project_members(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),user_id TEXT NOT NULL REFERENCES users(id),role TEXT NOT NULL CHECK(role IN ('OWNER','MANAGER','CREATOR','REVIEWER','VIEWER')),status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','REVOKED')),created_at TEXT NOT NULL,UNIQUE(project_id,user_id));
INSERT INTO project_members SELECT lower(hex(randomblob(16))),id,owner_id,'OWNER','ACTIVE',created_at FROM projects;
CREATE TRIGGER project_owner_member AFTER INSERT ON projects BEGIN INSERT INTO project_members VALUES(lower(hex(randomblob(16))),NEW.id,NEW.owner_id,'OWNER','ACTIVE',NEW.created_at); INSERT INTO audit_events(project_id,actor_user_id,event_type,target_type,target_id,created_at) VALUES(NEW.id,NEW.owner_id,'PROJECT_CREATED','project',NEW.id,NEW.created_at); END;
CREATE TABLE project_invites(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),token_hash TEXT NOT NULL UNIQUE,email TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('MANAGER','CREATOR','REVIEWER','VIEWER')),created_by TEXT NOT NULL REFERENCES users(id),expires_at TEXT NOT NULL,consumed_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE api_keys(key_id TEXT PRIMARY KEY,key_hash TEXT NOT NULL UNIQUE,user_id TEXT NOT NULL REFERENCES users(id),project_id TEXT REFERENCES projects(id),name TEXT NOT NULL,scopes TEXT NOT NULL,created_at TEXT NOT NULL,last_used_at TEXT,revoked_at TEXT);
CREATE TABLE version_sources(asset_version_id TEXT PRIMARY KEY REFERENCES asset_versions(id),external_source_url TEXT NOT NULL);
CREATE TRIGGER source_no_update BEFORE UPDATE ON version_sources BEGIN SELECT RAISE(ABORT,'source is immutable'); END;
CREATE TRIGGER source_no_delete BEFORE DELETE ON version_sources BEGIN SELECT RAISE(ABORT,'source is permanent'); END;
CREATE TABLE deliveries(id TEXT PRIMARY KEY,asset_version_id TEXT NOT NULL REFERENCES asset_versions(id),delivered_by TEXT NOT NULL REFERENCES users(id),delivered_at TEXT NOT NULL,recipient_user_id TEXT NOT NULL REFERENCES users(id),received_at TEXT,receipt_status TEXT NOT NULL DEFAULT 'DELIVERED' CHECK(receipt_status IN ('DELIVERED','RECEIVED','REJECTED')),comment TEXT NOT NULL DEFAULT '');
CREATE TABLE delivery_history(id INTEGER PRIMARY KEY AUTOINCREMENT,delivery_id TEXT NOT NULL REFERENCES deliveries(id),status TEXT NOT NULL,actor_user_id TEXT NOT NULL REFERENCES users(id),comment TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL);
CREATE TRIGGER delivery_identity_guard BEFORE UPDATE ON deliveries WHEN OLD.receipt_status!='DELIVERED' OR NEW.receipt_status NOT IN ('RECEIVED','REJECTED') OR NEW.id!=OLD.id OR NEW.asset_version_id!=OLD.asset_version_id OR NEW.delivered_by!=OLD.delivered_by OR NEW.delivered_at!=OLD.delivered_at OR NEW.recipient_user_id!=OLD.recipient_user_id BEGIN SELECT RAISE(ABORT,'delivery is immutable'); END;
CREATE TRIGGER delivery_no_delete BEFORE DELETE ON deliveries BEGIN SELECT RAISE(ABORT,'delivery is permanent'); END;
CREATE TRIGGER delivery_history_no_update BEFORE UPDATE ON delivery_history BEGIN SELECT RAISE(ABORT,'history is immutable'); END;
CREATE TRIGGER delivery_history_no_delete BEFORE DELETE ON delivery_history BEGIN SELECT RAISE(ABORT,'history is permanent'); END;
CREATE TABLE business_inquiries(id TEXT PRIMARY KEY,name TEXT NOT NULL,company TEXT NOT NULL,email TEXT NOT NULL,team_size TEXT NOT NULL,current_tools TEXT NOT NULL,problem TEXT NOT NULL,message TEXT NOT NULL,created_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'NEW');
ALTER TABLE webauthn_credentials ADD COLUMN name TEXT NOT NULL DEFAULT 'Passkey';
CREATE TRIGGER last_passkey_guard BEFORE DELETE ON webauthn_credentials WHEN (SELECT count(*) FROM webauthn_credentials WHERE recipient_id=OLD.recipient_id)<=1 BEGIN SELECT RAISE(ABORT,'last passkey cannot be removed'); END;
