import {env,applyD1Migrations} from 'cloudflare:test';
import {it,expect} from 'vitest';
import {id,now} from '../src/domain';
it('0017/0018は別Asset・FINAL・Proof・承認・納品・監査を統合や書換なしで保持しカウンターとBitcoin検証用の項目だけ追加',async()=>{
 const migrations=(env as unknown as {TEST_MIGRATIONS:Parameters<typeof applyD1Migrations>[1]}).TEST_MIGRATIONS;await applyD1Migrations(env.DB,migrations.slice(0,16));const owner=id(),reviewer=id(),project=id(),assets=[id(),id()],versions=[id(),id()],time=now();
 for(const user of [owner,reviewer])await env.DB.prepare('INSERT INTO users(id,display_name,created_at) VALUES(?,?,?)').bind(user,'Existing account',time).run();await env.DB.prepare('INSERT INTO projects(id,name,owner_id,created_at) VALUES(?,?,?,?)').bind(project,'Existing project',owner,time).run();await env.DB.prepare('INSERT INTO project_members(id,project_id,user_id,role,status,created_at) VALUES(?,?,?,?,?,?)').bind(id(),project,reviewer,'REVIEWER','ACTIVE',time).run();
 for(let i=0;i<2;i++){const filename=`Rahab_v${i+1}.${i?'mp4':'MP4'}`;await env.DB.prepare('INSERT INTO assets(id,project_id,filename,mime_type,size,created_at,created_by) VALUES(?,?,?,?,?,?,?)').bind(assets[i],project,filename,'video/mp4',3,time,owner).run();await env.DB.prepare('INSERT INTO asset_versions(id,asset_id,version,sha256,status,created_by,filename,mime_type,size,created_at) VALUES(?,?,1,?,?,?,?,?,?,?)').bind(versions[i],assets[i],'d'.repeat(64),'SUBMITTED',owner,filename,'video/mp4',3,time).run();await env.DB.prepare('INSERT INTO proofs(id,asset_version_id,sha256,created_at,ots_proof,proof_status,timestamp_status,bitcoin_status) VALUES(?,?,?,?,?,?,?,?)').bind(id(),versions[i],'d'.repeat(64),time,'retained-ots-evidence','WAITING_BITCOIN','PENDING','PENDING').run();await env.DB.prepare("UPDATE asset_version_states SET status='APPROVED',actor_user_id=?,reason=?,updated_at=? WHERE asset_version_id=?").bind(owner,'Historical approval',time,versions[i]).run();await env.DB.prepare("UPDATE asset_version_states SET status='FINAL',actor_user_id=?,updated_at=? WHERE asset_version_id=?").bind(owner,time,versions[i]).run();}
 await env.DB.prepare('INSERT INTO deliveries(id,asset_version_id,delivered_by,delivered_at,recipient_user_id,comment) VALUES(?,?,?,?,?,?)').bind(id(),versions[0],owner,time,reviewer,'Historical delivery').run();await env.DB.prepare('INSERT INTO review_comments(id,artifact_id,version_id,reviewer_id,reviewer_name,comment,created_at) VALUES(?,?,?,?,?,?,?)').bind(id(),assets[0],versions[0],reviewer,'Historical name','Historical review',time).run();
 const tables=['users','project_members','assets','asset_versions','asset_version_states','asset_version_state_history','approvals','deliveries','delivery_history','proofs','review_comments','audit_events'],before=await Promise.all(tables.map(async t=>(await env.DB.prepare(`SELECT * FROM ${t} ORDER BY 1`).all()).results));await applyD1Migrations(env.DB,migrations);
 for(const [i,t] of tables.entries()){const after=(await env.DB.prepare(`SELECT * FROM ${t} ORDER BY 1`).all()).results;expect(after.map(r=>{const old={...r};if(t==='assets')delete old.name;if(t==='proofs')for(const key of ['bitcoin_block_height','bitcoin_block_hash','bitcoin_block_time','bitcoin_verification_state'])delete old[key];if(t==='asset_version_state_history')delete old.actor_role;if(t==='approvals')delete old.approver_role;return old;})).toEqual(before[i]);}expect((await env.DB.prepare('SELECT * FROM asset_version_counters ORDER BY asset_id').all()).results).toEqual(assets.sort().map(asset_id=>({asset_id,next_version:2})));
});
