import {env,applyD1Migrations} from 'cloudflare:test';
import {beforeAll,it,expect} from 'vitest';
import worker from '../src/index';
import {id,now,sha256} from '../src/domain';
import {type Bindings} from '../src/store';
const bindings={...env,APP_ORIGIN:'http://localhost:8787',RP_ID:'localhost',OPERATOR_TOKEN:'test-operator'} as Bindings;
const owner=id(),other=id(),secret=id(),otherSecret=id();
let projectId:string,assetId:string,proofId:string,creatorId:string;
async function req(path:string,body?:unknown,cookie:string|null=secret,origin=bindings.APP_ORIGIN){return worker.fetch(new Request(bindings.APP_ORIGIN+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,...(cookie?{Cookie:`punka_session=${cookie}`}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})}),bindings);}
const file={filename:'final.png',mime_type:'image/png',size:3,sha256:'a'.repeat(64),comment:'初稿'};
beforeAll(async()=>{await applyD1Migrations(env.DB,(env as unknown as {TEST_MIGRATIONS:Parameters<typeof applyD1Migrations>[1]}).TEST_MIGRATIONS);for(const [u,t] of [[owner,secret],[other,otherSecret]]){await env.DB.prepare('INSERT INTO users(id,created_at) VALUES(?,?)').bind(u,now()).run();await env.DB.prepare('INSERT INTO sessions VALUES(?,?,?)').bind(await sha256(t),u,new Date(Date.now()+3600000).toISOString()).run();}});
it('旧API・MCPを停止し認証を要求する',async()=>{expect((await req('/api/issuance-batches',{})).status).toBe(410);expect((await req('/mcp/tools')).status).toBe(410);expect((await req('/api/projects',undefined,null)).status).toBe(401);expect((await req('/api/auth/passkey/register/options',{invite:'a'.repeat(64),consent:true},null)).status).toBe(410);});
it('案件・制作者を登録し所有者をサーバーで設定する',async()=>{const r=await req('/api/projects',{name:'Punka ボカロ楽曲',client_name:'Punka',start_date:'2026-10-01',end_date:'2026-11-01'});expect(r.status).toBe(201);const p=await r.json() as any;projectId=p.id;expect(p.owner_id).toBe(owner);const c=await req(`/api/projects/${projectId}/creators`,{name:'秘密の名前',email:'private@example.com',role:'Mix'});expect(c.status).toBe(201);creatorId=(await c.json() as any).id;});
it('制作物・初版・未取得証跡を原子的に登録する',async()=>{const r=await req(`/api/projects/${projectId}/assets`,{...file,creator_id:creatorId});expect(r.status).toBe(201);const a=await r.json() as any;assetId=a.id;proofId=a.proof_id;expect(a.version).toBe(1);const detail=await (await req(`/api/assets/${assetId}`)).json() as any;expect(detail.versions[0].sha256).toBe(file.sha256);expect(detail.versions[0].creator_name).toBe('秘密の名前');});
it('同時登録でも版番号を重複させず以前の履歴を保つ',async()=>{const responses=await Promise.all([req(`/api/assets/${assetId}/versions`,{...file,sha256:'b'.repeat(64),filename:'final2.png'}),req(`/api/assets/${assetId}/versions`,{...file,sha256:'c'.repeat(64),filename:'final3.png'})]);expect(responses.every(r=>[201,409].includes(r.status))).toBe(true);const a=await (await req(`/api/assets/${assetId}`)).json() as any;const versions=a.versions.map((v:any)=>v.version);expect(new Set(versions).size).toBe(versions.length);expect(versions).toEqual(Array.from({length:versions.length},(_,i)=>versions.length-i));expect(a.versions.at(-1).sha256).toBe(file.sha256);});
it('公開Verifyの許可フィールドに個人情報を含めない',async()=>{expect((await req(`/api/verify/${proofId}`,undefined,null)).status).toBe(404);bindings.PUBLIC_PROOF_IDS=proofId;const r=await req(`/api/verify/${proofId}`,undefined,null);expect(r.status).toBe(200);const p=await r.json() as any;expect(Object.keys(p).sort()).toEqual(['id','sha256','created_at','timestamp_status','bitcoin_status','timestamp','proof_status','timestamp_created_at','bitcoin_confirmed_at','bitcoin_block_height','bitcoin_block_hash','bitcoin_block_time','verification'].sort());expect(p.timestamp_status).toBe('NOT_REQUESTED');expect(p.bitcoin_status).toBe('NOT_REQUESTED');expect(p.timestamp).toBeNull();expect(p.verification.state).toBe('NOT_REQUESTED');expect(p).not.toHaveProperty('ots_proof');expect(p).not.toHaveProperty('project_id');expect((await req(`/api/verify/${id()}`,undefined,null)).status).toBe(404);});
it('別ユーザーからの閲覧・登録を拒否する',async()=>{for(const path of [`/api/projects/${projectId}`,`/api/assets/${assetId}`,`/api/proofs/${proofId}`])expect((await req(path,undefined,otherSecret)).status).toBe(404);expect((await req(`/api/assets/${assetId}/versions`,file,otherSecret)).status).toBe(404);expect(await (await req('/api/assets',undefined,otherSecret)).json()).toEqual([]);});
it('入力偽装・承認偽装・外部Origin・別案件制作者を拒否する',async()=>{expect((await req(`/api/assets/${assetId}/versions`,{...file,status:'FINAL'})).status).toBe(400);expect((await req(`/api/assets/${assetId}/versions`,{...file,sha256:'invalid'})).status).toBe(400);expect((await req(`/api/assets/${assetId}/versions`,{...file,file_body:'secret'})).status).toBe(400);expect((await req('/api/projects',{name:'x'},secret,'https://evil.example')).status).toBe(403);expect((await req('/api/projects',{name:'x',start_date:'2026-12-01',end_date:'2026-01-01'})).status).toBe(400);const p=await (await req('/api/projects',{name:'別案件'})).json() as any;expect((await req(`/api/projects/${p.id}/assets`,{...file,creator_id:creatorId})).status).toBe(400);});
it('履歴とハッシュの上書き・削除をDBでも拒否する',async()=>{await expect(env.DB.prepare('UPDATE asset_versions SET sha256=? WHERE asset_id=?').bind('f'.repeat(64),assetId).run()).rejects.toThrow();await expect(env.DB.prepare('DELETE FROM asset_versions WHERE asset_id=?').bind(assetId).run()).rejects.toThrow();await expect(env.DB.prepare('UPDATE proofs SET sha256=? WHERE id=?').bind('f'.repeat(64),proofId).run()).rejects.toThrow();});
it('初期セッションは管理者トークンと既存ユーザーが必要',async()=>{expect((await req('/api/auth/owner-session',{user_id:owner},null)).status).toBe(403);const r=await worker.fetch(new Request(bindings.APP_ORIGIN+'/api/auth/owner-session',{method:'POST',headers:{Origin:bindings.APP_ORIGIN,Authorization:'Bearer test-operator'},body:JSON.stringify({user_id:owner})}),bindings);expect(r.status).toBe(200);expect(r.headers.get('Set-Cookie')).toContain('HttpOnly');});
it('Passkey基盤を継続し、追加登録はログイン中だけ許可する',async()=>{expect((await req('/api/auth/passkey/register/options',{},null)).status).toBe(401);const r=await req('/api/auth/passkey/register/options',{});expect(r.status).toBe(200);const options=await r.json() as any;expect(options.rp.name).toBe('Creator Trace');expect(options.rp.id).toBe('localhost');expect(options.challenge).toBeTruthy();expect(r.headers.get('Set-Cookie')).toContain('HttpOnly');expect((await req('/api/auth/passkey/login/options',{},null)).status).toBe(200);expect(await (await req('/api/auth/session',undefined,null)).json()).toEqual({authenticated:false});});

it('公開対象外のOTSを拒否し、明示された音楽Proofだけ証跡をダウンロードできる',async()=>{
 bindings.PUBLIC_PROOF_IDS='';expect((await req(`/api/verify/${proofId}/ots`,undefined,null)).status).toBe(404);
 bindings.PUBLIC_PROOF_IDS=proofId;expect((await req(`/api/verify/${proofId}/ots`,undefined,null)).status).toBe(409);
 const fixture=(env as unknown as {TEST_OTS:string}).TEST_OTS,bytes=Buffer.from(fixture,'base64');
 const created=await (await req(`/api/projects/${projectId}/assets`,{...file,filename:'own-test-music.wav',sha256:bytes.subarray(33,65).toString('hex')})).json() as any;
 await env.DB.prepare('UPDATE proofs SET ots_proof=?,timestamp_created_at=? WHERE id=?').bind(fixture,now(),created.proof_id).run();bindings.PUBLIC_PROOF_IDS=created.proof_id;
 const response=await req(`/api/verify/${created.proof_id}/ots`,undefined,null);expect(response.status).toBe(200);expect(response.headers.get('Content-Disposition')).toContain('.ots');expect(Buffer.from(await response.arrayBuffer()).toString('base64')).toBe(fixture);
 expect((await req(`/api/verify/${proofId}`,undefined,null)).status).toBe(404);
});
