import {env,applyD1Migrations} from 'cloudflare:test';
import {beforeAll,it,expect,vi,afterEach} from 'vitest';
import worker from '../src/index';
import {id,now,sha256} from '../src/domain';
import {type Bindings} from '../src/store';
const bindings={...env,APP_ORIGIN:'http://localhost:8787',RP_ID:'localhost'} as Bindings;
const users=Object.fromEntries(['OWNER','MANAGER','CREATOR','REVIEWER','VIEWER'].map(r=>[r,id()]));let project:string,asset:string,v1:string;
async function req(path:string,body?:unknown,role='OWNER'){return worker.fetch(new Request(bindings.APP_ORIGIN+path,{method:body===undefined?'GET':'POST',headers:{Origin:bindings.APP_ORIGIN,Cookie:`punka_session=${users[role]}`,'CF-Connecting-IP':'version-approval-tests'},...(body===undefined?{}:{body:JSON.stringify(body)})}),bindings);}
const file=(filename:string,status='SUBMITTED')=>({filename,size:5,sha256:'b'.repeat(64),status});
async function create(role='OWNER',status='SUBMITTED'){const r=await req(`/api/projects/${project}/assets`,{name:"Rahab's mission Full HD 1080p",...file('Rahabs-mission_Full-HD-1080p_v1.MP4',status)},role);expect(r.status).toBe(201);return await r.json() as any;}
beforeAll(async()=>{await applyD1Migrations(env.DB,(env as unknown as {TEST_MIGRATIONS:Parameters<typeof applyD1Migrations>[1]}).TEST_MIGRATIONS);for(const [role,user] of Object.entries(users)){await env.DB.prepare('INSERT INTO users(id,display_name,created_at) VALUES(?,?,?)').bind(user,role,now()).run();await env.DB.prepare('INSERT INTO sessions VALUES(?,?,?)').bind(await sha256(user),user,new Date(Date.now()+86400000).toISOString()).run();}project=(await (await req('/api/projects',{name:'Version workflow'})).json() as any).id;for(const role of ['MANAGER','CREATOR','REVIEWER','VIEWER'])await env.DB.prepare('INSERT INTO project_members(id,project_id,user_id,role,status,created_at) VALUES(?,?,?,?,?,?)').bind(id(),project,users[role],role,'ACTIVE',now()).run();const a=await create();asset=a.id;v1=a.version_id;});
afterEach(()=>vi.restoreAllMocks());
it('新規v1・修正版v2/v3を同一asset_idへ追加し、論理名と最新版ファイルを分離',async()=>{
 for(const [n,name] of [[2,'Rahabs-mission_Full-HD-1080p_v2.mp4'],[3,'different_filename.MP4']] as const){const r=await req(`/api/assets/${asset}/versions`,file(name));expect(r.status).toBe(201);expect(await r.json()).toMatchObject({asset_id:asset,version:n,filename:name});}
 const a=await (await req(`/api/assets/${asset}`)).json() as any;expect(a.name).toBe("Rahab's mission Full HD 1080p");expect(a.versions.map((v:any)=>v.version)).toEqual([3,2,1]);expect(a.latest_version).toBe(3);expect(a.latest_filename).toBe('different_filename.MP4');expect(a.versions[2].id).toBe(v1);
 const list=(await (await req(`/api/projects/${project}`)).json() as any).assets;expect(list[0]).toMatchObject({id:asset,name:a.name,latest_version:3,latest_filename:a.latest_filename});
 expect((await req(`/api/assets/${asset}/versions`,{...file('v4.mp4'),version:4})).status).toBe(400);
});
it('同時登録12件の採番は重複せず、全VersionとProofが残る',async()=>{const responses=await Promise.all(Array.from({length:12},(_,i)=>req(`/api/assets/${asset}/versions`,file(`parallel-${i}.mp4`))));for(const r of responses)expect(r.status).toBe(201);const data=await Promise.all(responses.map(r=>r.json() as Promise<any>));expect(data.map(v=>v.version).sort((a,b)=>a-b)).toEqual(Array.from({length:12},(_,i)=>i+4));expect(new Set(data.map(v=>v.id)).size).toBe(12);expect(data.every(v=>v.asset_id===asset)).toBe(true);const rows=(await env.DB.prepare('SELECT v.id FROM asset_versions v JOIN proofs p ON p.asset_version_id=v.id WHERE v.asset_id=?').bind(asset).all()).results;expect(rows).toHaveLength(15);});
it('Version番号重複と過去Version変更を拒否、失敗時は採番もトランザクションで戻る',async()=>{
 const old=await env.DB.prepare('SELECT * FROM asset_versions WHERE id=?').bind(v1).first<any>();await expect(env.DB.prepare('INSERT INTO asset_versions(id,asset_id,version,sha256,status,created_by,filename,mime_type,size,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id(),asset,1,'c'.repeat(64),'SUBMITTED',users.OWNER,'duplicate','video/mp4',1,now()).run()).rejects.toThrow();await expect(env.DB.prepare('UPDATE asset_versions SET filename=? WHERE id=?').bind('tamper',v1).run()).rejects.toThrow();await expect(env.DB.prepare('DELETE FROM asset_versions WHERE id=?').bind(v1).run()).rejects.toThrow();
 const before=await env.DB.prepare('SELECT * FROM asset_version_counters WHERE asset_id=?').bind(asset).first<any>(),proof=await env.DB.prepare('SELECT id FROM proofs WHERE asset_version_id=?').bind(v1).first<any>(),version=id();await expect(env.DB.batch([env.DB.prepare('UPDATE asset_version_counters SET next_version=next_version+1 WHERE asset_id=?').bind(asset),env.DB.prepare('INSERT INTO asset_versions(id,asset_id,version,sha256,status,created_by,filename,mime_type,size,created_at) SELECT ?,?,next_version-1,?,?,?,?,?,?,? FROM asset_version_counters WHERE asset_id=?').bind(version,asset,'b'.repeat(64),'SUBMITTED',users.OWNER,'rolled-back.mp4','video/mp4',1,now(),asset),env.DB.prepare('INSERT INTO proofs(id,asset_version_id,sha256,created_at) VALUES(?,?,?,?)').bind(proof.id,version,'b'.repeat(64),now())])).rejects.toThrow();expect(await env.DB.prepare('SELECT * FROM asset_version_counters WHERE asset_id=?').bind(asset).first()).toEqual(before);expect(await env.DB.prepare('SELECT id FROM asset_versions WHERE id=?').bind(version).first()).toBeNull();expect(await env.DB.prepare('SELECT * FROM asset_versions WHERE id=?').bind(v1).first()).toEqual(old);
});
it.each(['OWNER','MANAGER','REVIEWER'])('%sの承認・差戻しコメントと当時Role・監査を追記保存する',async role=>{const a=await create(),b=await create();expect((await req(`/api/asset-versions/${a.version_id}/approve`,{comment:' 内容を確認しました。 '},role)).status).toBe(200);expect((await req(`/api/asset-versions/${b.version_id}/reject`,{comment:' 動画末尾を修正してください。 '},role)).status).toBe(200);const rows=(await env.DB.prepare('SELECT * FROM approvals WHERE asset_version_id IN (?,?) ORDER BY created_at,rowid').bind(a.version_id,b.version_id).all()).results;expect(rows.map(r=>[r.status,r.comment,r.approver_role])).toEqual([['APPROVED','内容を確認しました。',role],['REJECTED','動画末尾を修正してください。',role]]);const events=(await env.DB.prepare("SELECT metadata_json FROM audit_events WHERE target_id=? AND event_type='VERSION_APPROVED'").bind(a.version_id).all()).results;expect(JSON.parse(String(events[0].metadata_json))).toMatchObject({asset_id:a.id,asset_version_id:a.version_id,version:1,actor_role:role});await expect(env.DB.prepare('UPDATE approvals SET comment=? WHERE asset_version_id=?').bind('overwrite',a.version_id).run()).rejects.toThrow();vi.spyOn(globalThis,'fetch').mockRejectedValue(new Error('offline'));expect((await req(`/api/asset-versions/${a.version_id}/finalize`,{},role)).status).toBe(role==='OWNER'?200:403);});
it('承認コメントは省略可能、差戻し空文字・空白は400で状態を変えない',async()=>{const a=await create(),b=await create();expect((await req(`/api/asset-versions/${a.version_id}/approve`,{},'MANAGER')).status).toBe(200);expect((await env.DB.prepare('SELECT comment FROM approvals WHERE asset_version_id=?').bind(a.version_id).first<any>()).comment).toBe('');for(const comment of ['', '   '])expect((await req(`/api/asset-versions/${b.version_id}/reject`,{comment},'REVIEWER')).status).toBe(400);expect((await env.DB.prepare('SELECT status FROM asset_version_states WHERE asset_version_id=?').bind(b.version_id).first<any>()).status).toBe('SUBMITTED');});
it('CREATORは自分のDRAFT提出可能、承認・FINAL不可。VIEWERは案件内の全更新不可',async()=>{const a=await create('CREATOR','DRAFT');expect((await req(`/api/asset-versions/${a.version_id}/submit`,{},'CREATOR')).status).toBe(200);for(const role of ['CREATOR','VIEWER'])for(const action of ['approve','finalize'])expect((await req(`/api/asset-versions/${a.version_id}/${action}`,{},role)).status).toBe(403);for(const [path,body] of [[`/api/projects/${project}/assets`,file('x.mp4')],[`/api/assets/${asset}/versions`,file('x.mp4')],[`/api/asset-versions/${a.version_id}/submit`,{}],[`/api/asset-versions/${a.version_id}/reject`,{comment:'x'}],[`/api/projects/${project}/bot-reviews`,{assetVersionId:a.version_id}]] as const)expect((await req(path,body,'VIEWER')).status).toBe(403);});
it.each(['DRAFT','SUBMITTED','REJECTED'])('OWNERでも%sからFINALは409',async status=>{const a=await create('OWNER',status==='DRAFT'?'DRAFT':'SUBMITTED');if(status==='REJECTED')expect((await req(`/api/asset-versions/${a.version_id}/reject`,{comment:'needs revision'})).status).toBe(200);expect((await req(`/api/asset-versions/${a.version_id}/finalize`,{})).status).toBe(409);});
it('招待のlimit=3は最新3件、PENDINGは全件、過去履歴はDBと既存APIへ全件保持',async()=>{for(let i=0;i<5;i++){const r=await req(`/api/projects/${project}/invites`,{email:`history-${i}@example.com`,role:'CREATOR'});expect(r.status).toBe(201);const invite=await r.json() as any;await env.DB.prepare('UPDATE project_invites SET created_at=? WHERE id=?').bind(`2026-10-02T0${i}:00:00.000Z`,invite.id).run();}const latest=await (await req(`/api/projects/${project}/invites?limit=3`)).json() as any[];expect(latest.map(r=>r.email)).toEqual(['history-4@example.com','history-3@example.com','history-2@example.com']);expect(await (await req(`/api/projects/${project}/invites?status=PENDING`)).json()).toHaveLength(5);expect(await (await req(`/api/projects/${project}/invites`)).json()).toHaveLength(5);expect((await env.DB.prepare('SELECT count(*) AS n FROM project_invites WHERE project_id=?').bind(project).first<any>()).n).toBe(5);});
