import {test,expect} from './fixtures';
import {createHash} from 'node:crypto';
test('案件・既存制作者履歴・ファイル・修正版を保持し非公開画面で照合する',async({page,browser})=>{
 await page.goto('/setup');
 await page.getByLabel('ユーザーID').fill('11111111-1111-4111-8111-111111111111');
 await page.getByLabel('初期設定トークン').fill('e2e-operator-only');
 await page.getByRole('button',{name:'登録する'}).click();
 await expect(page).toHaveURL(/\/settings\/security$/);
 await expect(page.getByText('登録済み：0件')).toBeVisible();
 await page.goto('/projects');
 await page.getByLabel('案件名',{exact:true}).fill('Punka 楽曲制作');
 await page.getByLabel('クライアント名').fill('秘密のクライアント');
 await page.getByRole('button',{name:'登録する'}).click();
 await expect(page.getByRole('heading',{name:'Punka 楽曲制作',exact:true})).toBeVisible();
 await expect(page.getByRole('heading',{name:'担当者・制作者を登録'})).toHaveCount(0);
 // Seed a legacy credit through the retained API; the registration UI is gone.
 const projectId=new URL(page.url()).pathname.split('/').at(-1)!;
 expect((await page.request.post(`/api/projects/${projectId}/creators`,{headers:{Origin:new URL(page.url()).origin},data:{name:'秘密の制作者',email:'private@example.com',role:'Mix'}})).status()).toBe(201);
 await page.reload();await page.getByText('過去の担当者・制作者',{exact:true}).click();
 await expect(page.locator('p').filter({hasText:'秘密の制作者 / Mix'})).toBeVisible();
 const file=page.locator('form').filter({has:page.getByRole('heading',{name:'新しい制作物を登録',exact:true})});
 await file.getByLabel('制作物名').fill('Punka 楽曲');await file.getByLabel('ファイル',{exact:true}).setInputFiles({name:'final.wav',mimeType:'audio/wav',buffer:Buffer.from('version one')});
 await file.getByLabel('制作者',{exact:true}).selectOption({label:'秘密の制作者 / Mix'});await file.getByLabel('変更内容・納品コメント').fill('初稿');await file.getByRole('button',{name:'新しい制作物を登録',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Punka 楽曲',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Version 1 ・最新版'})).toBeVisible();
 const revision=page.locator('form').filter({has:page.getByRole('heading',{name:'修正版を登録'})});
 const bytes=Buffer.from('version two');await revision.getByLabel('ファイル',{exact:true}).setInputFiles({name:'final2.wav',mimeType:'audio/wav',buffer:bytes});await revision.getByLabel('変更内容・納品コメント').fill('音量修正');await revision.getByRole('button',{name:'修正版を登録',exact:true}).click();
 await expect(page.getByText('最新版ファイル：final2.wav',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Punka 楽曲',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Version 2 ・最新版'})).toBeVisible();await expect(page.getByRole('heading',{name:'Version 1',exact:true})).toBeVisible();
 const latest=page.locator('section').filter({has:page.getByRole('heading',{name:'Version 2 ・最新版'})});
 await latest.getByRole('button',{name:'承認する',exact:true}).click();
 await latest.getByRole('button',{name:'FINALに確定',exact:true}).click();
 const recipient=latest.getByRole('combobox',{name:'受領者',exact:true});await expect(recipient).toBeVisible();
 await expect(recipient.locator('option')).toHaveText(['受領者を選択してください','Punka']);
 await expect(latest.locator('input[name="recipient_user_id"]')).toHaveCount(0);
 await recipient.selectOption({label:'Punka'});await latest.getByLabel('納品コメント',{exact:true}).fill('TEST');
 const deliveryRequest=page.waitForRequest(r=>r.method()==='POST'&&r.url().endsWith('/deliveries'));
 await latest.getByRole('button',{name:'納品を記録'}).click();
 expect((await deliveryRequest).postDataJSON()).toEqual({recipient_user_id:'11111111-1111-4111-8111-111111111111',comment:'TEST'});
 await expect(latest.getByText(/納品 .*DELIVERED/)).toBeVisible();
 await latest.getByRole('button',{name:'受領する',exact:true}).click();await expect(latest.getByText(/納品 .*RECEIVED/)).toBeVisible();
 await page.route('**/api/projects/*/members',route=>route.fulfill({json:[]}));await page.reload();
 await expect(latest.getByText('この案件には受領者として選択できるメンバーがいません')).toBeVisible();
 await expect(latest.getByRole('button',{name:'納品を記録'})).toHaveCount(0);
 await expect(latest.getByText(/納品 .*RECEIVED/)).toBeVisible();
 await page.unroute('**/api/projects/*/members');
 await page.getByRole('link',{name:'証跡詳細'}).first().click();
 await expect(page.getByText(createHash('sha256').update(bytes).digest('hex'),{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'ファイルと証跡を確認する'}).click();
 await expect(page.getByRole('heading',{name:'ファイルと証跡の確認',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'公開Verifyを開く'})).toHaveCount(0);
 await expect(page.locator('.proof-verification')).toContainText('Bitcoin確認状態');await expect(page.locator('.proof-verification')).not.toContainText('Confirmed');
 await page.getByLabel('確認するファイル').setInputFiles({name:'renamed.wav',mimeType:'audio/wav',buffer:bytes});await page.getByRole('button',{name:'ファイルを照合する'}).click();await expect(page.getByRole('status')).toContainText('SHA-256が一致しました');
 await page.getByLabel('確認するファイル').setInputFiles({name:'final2.wav',mimeType:'audio/wav',buffer:Buffer.from('different')});await page.getByRole('button',{name:'ファイルを照合する'}).click();await expect(page.getByRole('status')).toContainText('SHA-256が一致しません');
 const anon=await browser.newContext();const publicPage=await anon.newPage();await publicPage.goto(page.url().replace('/proof/','/verify/').replace('/check',''));await expect(publicPage.getByText('この証跡は公開されていません。案件メンバーは証跡詳細から確認してください',{exact:true})).toBeVisible();await expect(publicPage.getByLabel('確認するファイル')).toHaveCount(0);await anon.close();
});
