import {test,expect} from './fixtures';
import {installAuthenticator} from './authenticator';
test('Proof・招待・表示名・Passkey・参加・取消確認・再招待・履歴保全・XSS',async({page,browser})=>{
 test.setTimeout(120000);
 await page.goto('/setup');await page.getByLabel('ユーザーID').fill('11111111-1111-4111-8111-111111111111');await page.getByLabel('初期設定トークン').fill('e2e-operator-only');await page.getByRole('button',{name:'登録する'}).click();await expect(page).toHaveURL(/\/settings\/security$/);
 const headers={Origin:'http://localhost:8791'},project=await (await page.request.post('/api/projects',{headers,data:{name:"Rahab's mission"}})).json();
 const asset=await (await page.request.post(`/api/projects/${project.id}/assets`,{headers,data:{filename:'navigation.wav',size:3,sha256:'f'.repeat(64),status:'SUBMITTED'}})).json();
 await page.goto(`/proof/${asset.proof_id}`);const back=page.getByRole('link',{name:'← Version 1 に戻る'});await expect(back).toHaveAttribute('href',`/assets/${asset.id}/versions/${asset.version_id}`);await expect(page.getByRole('navigation',{name:'パンくず'})).toHaveText('案件＞制作物＞Version 1＞証跡詳細');await back.click();await expect(page).toHaveURL(`/assets/${asset.id}/versions/${asset.version_id}`);await expect(page.getByRole('heading',{name:'Version 1',exact:true}).first()).toBeVisible();
 await page.goto(`/projects/${project.id}`);await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(text:string)=>{(window as any).copiedInvite=text;}}});});
 const form=page.locator('form').filter({has:page.getByRole('heading',{name:'案件メンバーを招待'})});await form.getByLabel('招待先メール（連絡先）').fill('guest@example.com');await form.getByLabel('Role',{exact:true}).selectOption('CREATOR');let posts=0;let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});await page.route(`**/api/projects/${project.id}/invites`,async route=>{if(route.request().method()!=='POST'){await route.continue();return;}posts++;await gate;const response=await route.fetch();expect(response.status()).toBe(201);const result=await response.json();expect(result.id).toBeTruthy();expect(result.url).toBeTruthy();await route.fulfill({response,json:{id:result.id,url:result.url}});});await form.getByRole('button',{name:'メンバーを招待する'}).click();await expect(form.getByRole('button',{name:'招待作成中...'})).toBeDisabled();await form.evaluate(f=>{f.dispatchEvent(new Event('submit',{cancelable:true}));f.dispatchEvent(new Event('submit',{cancelable:true}));});release();await expect(page.getByText('招待を作成しました',{exact:true})).toBeVisible();expect(posts).toBe(1);await expect(form.getByLabel('招待先メール（連絡先）')).toHaveValue('');
 const url=page.getByLabel('招待URL',{exact:true});await expect(url).toBeVisible();const inviteURL=await url.inputValue();await expect(page.getByRole('button',{name:'招待URLをコピー',exact:true})).toBeFocused();await page.getByRole('button',{name:'招待URLをコピー',exact:true}).click();await expect(page.getByText('コピーしました')).toBeVisible();expect(await page.evaluate(()=>(window as any).copiedInvite)).toBe(inviteURL);await expect(page.locator('table').getByText('guest@example.com').first()).toBeVisible();
 await page.reload();await expect(page.getByLabel('招待URL',{exact:true})).toHaveCount(0);await expect(page.locator('table').getByText('guest@example.com').first()).toBeVisible();
 const context=await browser.newContext();const guest=await context.newPage();const authenticator=await installAuthenticator(guest);await guest.goto(inviteURL);await expect(guest.getByText("Rahab's mission",{exact:true})).toBeVisible();await expect(guest.getByText('guest@example.com',{exact:true})).toBeVisible();await guest.getByRole('link',{name:'初めての利用：Passkey登録'}).click();await guest.getByLabel('表示名').fill('招待ゲスト');await expect(guest.getByLabel('表示名')).toHaveAttribute('required','');await expect(guest.getByLabel('表示名')).toHaveAttribute('maxlength','50');await expect(guest.getByLabel('最初の案件名')).toHaveCount(0);await expect(guest.getByText('無料で試す',{exact:true})).toHaveCount(0);await guest.reload();await expect(guest.getByText("Rahab's mission",{exact:true})).toBeVisible();await guest.getByLabel('表示名').fill('招待ゲスト');await guest.getByRole('button',{name:'Passkeyを登録して参加する'}).click();
 await expect(guest).toHaveURL(`/projects/${project.id}?joined=1`);await expect(guest.getByText('案件への参加が完了しました',{exact:true})).toBeVisible();expect(authenticator.calls.map(c=>c.kind)).toEqual(['create']);expect(authenticator.calls[0].selection).toMatchObject({residentKey:'required',userVerification:'required'});expect(authenticator.calls[0].selection?.authenticatorAttachment).toBeUndefined();expect(authenticator.calls[0].hints).toContain('hybrid');await expect(guest.locator('table').getByText('招待ゲスト')).toBeVisible();await expect(guest.getByRole('button',{name:'メンバーを招待する'})).toHaveCount(0);
 await page.unroute(`**/api/projects/${project.id}/invites`);await page.reload();await expect(page.getByText('参加済み (ACCEPTED)',{exact:true})).toBeVisible();await expect(page.locator('table').getByText('招待ゲスト')).toBeVisible();await guest.goto(inviteURL);await expect(guest.getByText('参加済み (ACCEPTED)',{exact:true})).toBeVisible();await expect(guest.getByRole('button',{name:'案件へ参加する'})).toHaveCount(0);await guest.goto('/projects');const owned=await (await guest.request.get('/api/projects')).json();expect(owned.items??owned).toHaveLength(1);
 const second=await (await page.request.post(`/api/projects/${project.id}/invites`,{headers,data:{email:'second@example.com',role:'VIEWER'}})).json();await guest.goto('/settings/security');await guest.getByRole('button',{name:'ログアウト'}).click();await guest.goto(second.url);await guest.getByRole('link',{name:'登録済み：ログイン'}).click();await guest.reload();await expect(guest.getByText("Rahab's mission",{exact:true})).toBeVisible();await expect(guest.getByRole('link',{name:'初めての利用：Passkey登録'})).toHaveAttribute('href',second.url.replace('http://localhost:8791','')+'/signup');await expect(guest.getByText(/無料で試す/)).toHaveCount(0);await guest.getByRole('button',{name:'パスキーでログイン'}).click();await expect(guest).toHaveURL(second.url);expect(authenticator.calls.map(c=>c.kind)).toEqual(['create','get']);await guest.getByRole('button',{name:'案件へ参加する'}).click();await expect(guest.getByText('この案件にはすでに参加しています',{exact:true})).toBeVisible();const invitations=await (await page.request.get(`/api/projects/${project.id}/invites`)).json();expect(invitations.find((i:any)=>i.id===second.id).status).toBe('PENDING');
 const historyAssetResponse=await guest.request.post(`/api/projects/${project.id}/assets`,{headers,data:{filename:'guest-history.wav',sha256:'3'.repeat(64),size:3,status:'SUBMITTED'}});expect(historyAssetResponse.status()).toBe(201);const historyAsset=await historyAssetResponse.json();expect((await page.request.post(`/api/asset-versions/${historyAsset.version_id}/approve`,{headers,data:{reason:'Keep approval history'}})).status()).toBe(200);
 const historyBefore=await (await page.request.get(`/api/asset-versions/${historyAsset.version_id}/history`)).json();
 await page.goto(`/projects/${project.id}`);const memberRow=page.locator('table').first().getByRole('row').filter({hasText:'招待ゲスト'});await memberRow.getByRole('button',{name:'メンバーを外す'}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByText('過去の制作・納品・承認履歴は残りますが、今後この案件へアクセスできなくなります。')).toBeVisible();await dialog.getByRole('button',{name:'キャンセル'}).click();expect((await guest.request.get(`/api/projects/${project.id}`)).status()).toBe(200);
 await memberRow.getByRole('button',{name:'メンバーを外す'}).click();await dialog.getByRole('button',{name:'メンバーを外す',exact:true}).click();await expect(page.locator('table').first().getByText('招待ゲスト')).toHaveCount(0);expect((await guest.request.get(`/api/projects/${project.id}`)).status()).toBe(403);
 await page.getByText('過去のメンバー・取消履歴',{exact:true}).click();await expect(page.getByText(/招待ゲスト.*現在は案件メンバーではありません/)).toBeVisible();
 expect(await (await page.request.get(`/api/asset-versions/${historyAsset.version_id}/history`)).json()).toEqual(historyBefore);expect((await page.request.get(`/api/proofs/${historyAsset.proof_id}`)).status()).toBe(200);
 await page.goto(`/assets/${historyAsset.id}/versions/${historyAsset.version_id}`);await expect(page.getByText('登録者：招待ゲスト（現在は案件メンバーではありません）',{exact:true})).toBeVisible();
 const again=await (await page.request.post(`/api/projects/${project.id}/invites`,{headers,data:{email:'guest@example.com',role:'CREATOR'}})).json();await guest.goto(again.url);await expect(guest.getByLabel('表示名',{exact:true})).toHaveValue('招待ゲスト');const safeName='Rahab <script>alert(1)</script>';await guest.getByLabel('表示名',{exact:true}).fill(safeName);await guest.getByRole('button',{name:'案件へ参加する'}).click();await expect(guest.getByText('案件への参加が完了しました',{exact:true})).toBeVisible();await expect(guest.getByText(safeName,{exact:true})).toBeVisible();await expect(guest.locator('main script')).toHaveCount(0);await guest.getByRole('link',{name:'案件を開く',exact:true}).click();await expect(guest.locator('table').getByText(safeName,{exact:true})).toBeVisible();
 await page.goto(`/projects/${project.id}`);await expect(page.locator('table').first().getByText(safeName,{exact:true})).toBeVisible();await page.getByText('過去のメンバー・取消履歴',{exact:true}).click();await expect(page.getByText(/取消者：Punka.*現在は再参加済み/)).toBeVisible();await context.close();
});

for(const [status,message] of [[400,'入力内容を確認してください'],[403,'この案件ではメンバーを招待できません'],[409,'このメールアドレスには既に招待を送っています'],[410,'招待URLの有効期限が切れています'],[500,'招待の作成に失敗しました']] as const){
 test(`招待作成${status}の具体的なエラー表示`,async({page})=>{
  await page.goto('/setup');await page.getByLabel('ユーザーID').fill('11111111-1111-4111-8111-111111111111');await page.getByLabel('初期設定トークン').fill('e2e-operator-only');await page.getByRole('button',{name:'登録する'}).click();await expect(page).toHaveURL(/\/settings\/security$/);
  const project=await (await page.request.post('/api/projects',{headers:{Origin:'http://localhost:8791'},data:{name:`Invite error ${status}`}})).json();await page.goto(`/projects/${project.id}`);
  await page.route(`**/api/projects/${project.id}/invites`,async route=>{if(route.request().method()==='POST')await route.fulfill({status,json:{error:'入力内容が不正です'}});else await route.continue();});
  const form=page.locator('form').filter({has:page.getByRole('heading',{name:'案件メンバーを招待'})});await form.getByLabel('招待先メール（連絡先）').fill('error@example.com');await form.getByRole('button',{name:'メンバーを招待する'}).click();await expect(page.getByText(message,{exact:true})).toBeVisible();await expect(form.getByRole('button',{name:'メンバーを招待する'})).toBeEnabled();
 });
}
