import {test,expect} from './fixtures';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
test('テスト音源をブラウザー登録・非公開照合・実Calendar再確認・OTSダウンロード',async({page,browser})=>{
 test.setTimeout(150000);
 const artifacts=resolve('docs/screenshots');mkdirSync(artifacts,{recursive:true});
 await page.goto('/');await expect(page.getByRole('heading',{name:'どれが最新版？誰が承認した？をひと目で確認'})).toBeVisible();await expect(page.getByRole('heading',{name:'Rahab Punkaholic Girlsのボカロ楽曲制作から'})).toBeVisible();await page.screenshot({path:artifacts+'/homepage-mobile.png',fullPage:true});
 await page.goto('/setup');await page.getByLabel('ユーザーID').fill('11111111-1111-4111-8111-111111111111');await page.getByLabel('初期設定トークン').fill('e2e-operator-only');await page.getByRole('button',{name:'登録する'}).click();await expect(page).toHaveURL(/\/settings\/security$/);
 await page.goto('/projects');await page.getByLabel('案件名',{exact:true}).fill('証跡確認デモ（非公開）');await page.getByRole('button',{name:'登録する'}).click();await expect(page.getByRole('heading',{name:'証跡確認デモ（非公開）',exact:true})).toBeVisible();
 const file=page.locator('form').filter({has:page.getByRole('heading',{name:'新しい制作物を登録',exact:true})});await file.getByLabel('制作物名').fill('自作テスト音源');await file.getByLabel('ファイル',{exact:true}).setInputFiles(resolve('docs/demo-files/original.wav'));await file.getByLabel('変更内容・納品コメント').fill('既存案件を使わない動作確認');await file.getByRole('button',{name:'新しい制作物を登録',exact:true}).click();await expect(page.getByRole('heading',{name:'自作テスト音源',exact:true})).toBeVisible();
 await page.getByRole('link',{name:'証跡詳細',exact:true}).click();await expect(page.getByRole('heading',{name:'証跡詳細',exact:true})).toBeVisible();const proofId=new URL(page.url()).pathname.split('/')[2];
 await page.getByRole('link',{name:'ファイルと証跡を確認する'}).click();await expect(page.getByRole('heading',{name:'ファイルと証跡の確認',exact:true})).toBeVisible();await expect(page.locator('.proof-verification').getByText('未実行',{exact:true}).first()).toBeVisible();await expect(page.getByRole('link',{name:'公開Verifyを開く'})).toHaveCount(0);
 const requests:string[]=[];page.on('request',r=>{if(r.method()==='POST')requests.push(r.url());});
 await page.getByLabel('確認するファイル').setInputFiles(resolve('docs/demo-files/original.wav'));await page.getByRole('button',{name:'ファイルを照合する'}).click();await expect(page.getByRole('status')).toContainText('SHA-256が一致しました');await page.screenshot({path:artifacts+'/file-match-mobile.png',fullPage:true});
 await page.getByLabel('確認するファイル').setInputFiles({name:'original.wav',mimeType:'audio/wav',buffer:readFileSync(resolve('docs/demo-files/modified.wav'))});await page.getByRole('button',{name:'ファイルを照合する'}).click();await expect(page.getByRole('status')).toContainText('SHA-256が一致しません');expect(requests).toHaveLength(0);await page.setViewportSize({width:1280,height:900});await page.screenshot({path:artifacts+'/file-mismatch-desktop.png',fullPage:true});
 const before=await (await page.request.get(`/api/proofs/${proofId}`)).json();const versionBefore=await (await page.request.get(`/api/assets/${before.asset_id}/versions/${before.asset_version_id}`)).json();
 // No page routes, fetch mocks or canned calendar responses: real Worker -> external calendar request.
 const response=page.waitForResponse(r=>r.url().endsWith(`/api/proofs/${proofId}/retry`)&&r.request().method()==='POST');await page.getByRole('button',{name:'証跡を作成 / 再確認'}).click();expect((await response).status()).toBe(200);await page.waitForLoadState('networkidle');await expect.poll(async()=>{const r=await page.request.get(`/api/proofs/${proofId}`);return (await r.json()).retry_count;}).toBe(1);
 await expect(page.locator('.proof-verification')).toContainText('JST（UTC+09:00）');let after=await (await page.request.get(`/api/proofs/${proofId}`)).json();expect(after.bitcoin_status).not.toBe('CONFIRMED');expect(after.bitcoin_confirmed_at).toBeNull();expect(['WAITING_BITCOIN','VERIFY_FAILED','BITCOIN_ANCHOR_FOUND','OTS_CREATED']).toContain(after.verification.state);expect(after.sha256).toBe(before.sha256);
 const firstTimestamp=after.timestamp_created_at;console.log('LIVE_FIRST_CHECK',JSON.stringify({proof_status:after.proof_status,retry_count:after.retry_count,verification:after.verification}));
 // Respect the production cooldown; do not alter last_retry_at in the DB to force a retry.
 const remaining=Math.max(0,Date.parse(after.last_retry_at)+61000-Date.now());await page.waitForTimeout(remaining);
 const retryResponse=page.waitForResponse(r=>r.url().endsWith(`/api/proofs/${proofId}/retry`)&&r.request().method()==='POST');await page.getByRole('button',{name:'証跡を作成 / 再確認'}).click();expect((await retryResponse).status()).toBe(200);await expect.poll(async()=>{const r=await page.request.get(`/api/proofs/${proofId}`);return (await r.json()).retry_count;}).toBe(2);await page.waitForLoadState('networkidle');after=await (await page.request.get(`/api/proofs/${proofId}`)).json();expect(after.timestamp_created_at).toBe(firstTimestamp);expect(after.bitcoin_confirmed_at).toBeNull();
 const versionAfter=await (await page.request.get(`/api/assets/${before.asset_id}/versions/${before.asset_version_id}`)).json();for(const field of ['sha256','status','filename','version','created_at'])expect(versionAfter[field]).toBe(versionBefore[field]);
 if(after.verification.has_ots){const download=page.waitForEvent('download');await page.getByRole('link',{name:'OpenTimestamps証明ファイルをダウンロード'}).click();await (await download).saveAs(artifacts+'/demo-proof.ots');}
 await page.screenshot({path:artifacts+'/timestamp-result-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:artifacts+'/timestamp-result-mobile.png',fullPage:true});
 const summary={environment:'local isolated D1, live external OTS calendar',proofId,sha256:after.sha256,registered:after.created_at,timestamp_created_at:after.timestamp_created_at,bitcoin_confirmed_at:after.bitcoin_confirmed_at,proof_status:after.proof_status,retry_count:after.retry_count,verification:after.verification,version_unchanged:true,file_match:true,modified_file_match:false};writeFileSync(artifacts+'/verification-result.json',JSON.stringify(summary,null,2));console.log('LIVE_TIMESTAMP_RESULT',JSON.stringify(summary));
 const anon=await browser.newContext();const guest=await anon.newPage();await guest.goto(`http://localhost:8791/verify/${proofId}`);await expect(guest.getByText('この証跡は公開されていません。案件メンバーは証跡詳細から確認してください',{exact:true})).toBeVisible();await expect(guest.getByLabel('確認するファイル')).toHaveCount(0);await anon.close();
});
