import {test,expect} from './fixtures';
import {installAuthenticator} from './authenticator';
test('Reviewerコメントは制作物単位で保持・承認・差戻し可能でFINAL不可・全画面のログイン表示・OwnerとManagerが判断',async({page,browser})=>{
 test.setTimeout(120000);
 await page.goto('/setup');await page.getByLabel('ユーザーID').fill('11111111-1111-4111-8111-111111111111');await page.getByLabel('初期設定トークン').fill('e2e-operator-only');await page.getByRole('button',{name:'登録する'}).click();await expect(page).toHaveURL(/\/settings\/security$/);
 const headers={Origin:'http://localhost:8791'},project=await (await page.request.post('/api/projects',{headers,data:{name:'Reviewer workflow'}})).json();
 const asset=await (await page.request.post(`/api/projects/${project.id}/assets`,{headers,data:{filename:'review.wav',size:4,sha256:'9'.repeat(64),status:'SUBMITTED'}})).json();
 async function join(role:string,name:string,email:string){const invite=await (await page.request.post(`/api/projects/${project.id}/invites`,{headers,data:{email,role}})).json();const context=await browser.newContext({extraHTTPHeaders:{'CF-Connecting-IP':`reviewer-browser-${role}`}}),guest=await context.newPage();await installAuthenticator(guest);await guest.goto(`${invite.url}/signup`);await guest.getByLabel('表示名').fill(name);await guest.getByRole('button',{name:'Passkeyを登録して参加する'}).click();await expect(guest).toHaveURL(`/projects/${project.id}?joined=1`);await expect(guest.getByText('案件への参加が完了しました',{exact:true})).toBeVisible();await expect(guest.locator('#account-status')).toContainText(`ログイン中：${name}`);return {context,guest};}
 const {context,guest}=await join('REVIEWER','Rahab','reviewer@example.com');await guest.goto(`/assets/${asset.id}/versions/${asset.version_id}`);
 await expect(guest.locator('#account-status')).toContainText('ログイン中：Rahab');await expect(guest.getByRole('button',{name:'承認する',exact:true})).toBeVisible();await expect(guest.getByRole('button',{name:'差し戻す',exact:true})).toBeVisible();await expect(guest.getByRole('button',{name:'FINALに確定',exact:true})).toHaveCount(0);
 const section=guest.locator('.reviewer-comments');await section.getByLabel('コメント',{exact:true}).fill('歌詞部分の表記を確認してください');await section.getByRole('button',{name:'コメントを追加'}).click();await expect(section.getByText('コメントを追加しました',{exact:true})).toBeVisible();
 for(const action of ['finalize'])expect((await guest.request.post(`/api/asset-versions/${asset.version_id}/${action}`,{headers,data:{}})).status()).toBe(403);
 const v2=await (await page.request.post(`/api/assets/${asset.id}/versions`,{headers,data:{filename:'review-v2.wav',size:5,sha256:'a'.repeat(64),status:'SUBMITTED'}})).json();await guest.goto(`/assets/${asset.id}/versions/${v2.id}`);await expect(section.getByText('歌詞部分の表記を確認してください',{exact:true})).toBeVisible();await expect(section.getByRole('link',{name:'v1',exact:true})).toBeVisible();
 const safe='<script>alert(1)</script> 修正版を確認しました';await section.getByLabel('コメント',{exact:true}).fill(safe);await section.getByRole('button',{name:'コメントを追加'}).click();await expect(section.getByText(safe,{exact:true})).toBeVisible();await expect(guest.locator('main script')).toHaveCount(0);await expect(section.locator('article')).toHaveCount(2);await expect(section.locator('article').first()).toContainText('歌詞部分');await expect(section.locator('article').last()).toContainText('修正版');
 for(const path of ['/', '/projects','/assets',`/projects/${project.id}`,`/assets/${asset.id}`,`/assets/${asset.id}/versions/${v2.id}`,`/proof/${asset.proof_id}`,'/settings/security','/business']){await guest.goto(path);await expect(guest.locator('#account-status')).toContainText('Rahab');await expect(guest.locator('#account-status')).not.toContainText('Reviewer');await expect(guest.locator('#account-status').getByRole('button',{name:'ログアウト'})).toBeVisible();}
 for(const width of [1280,375,320]){await guest.setViewportSize({width,height:844});await expect(guest.locator('#account-status')).toBeVisible();const layout=await guest.locator('#account-status').evaluate(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,width:innerWidth};});expect(layout.left).toBeGreaterThanOrEqual(0);expect(layout.right).toBeLessThanOrEqual(layout.width);}
 await page.goto(`/assets/${asset.id}/versions/${v2.id}`);await expect(page.locator('#account-status')).toContainText('ログイン中：Punka');await expect(page.getByRole('button',{name:'承認する',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'差し戻す',exact:true})).toBeVisible();await page.getByRole('button',{name:'承認する',exact:true}).click();await expect(page.getByRole('button',{name:'FINALに確定',exact:true})).toBeVisible();
 const manager=await join('MANAGER','Manager user','manager@example.com');await manager.guest.goto(`/assets/${asset.id}/versions/${asset.version_id}`);await expect(manager.guest.locator('#account-status')).toContainText('ログイン中：Manager user');await expect(manager.guest.getByRole('button',{name:'承認する',exact:true})).toBeVisible();await manager.guest.getByLabel('差戻しコメント',{exact:true}).fill('動画末尾を修正してください');await manager.guest.getByRole('button',{name:'差し戻す',exact:true}).click();await expect(manager.guest.getByText('SUBMITTED → REJECTED',{exact:false})).toBeVisible();await expect(manager.guest.locator('.reviewer-comments article')).toHaveCount(2);expect((await manager.guest.request.post(`/api/asset-versions/${v2.id}/finalize`,{headers,data:{}})).status()).toBe(403);
 await guest.locator('#account-status').getByRole('button',{name:'ログアウト'}).click();await expect(guest).toHaveURL('/login');await expect(guest.locator('#account-status')).toBeEmpty();await context.close();await manager.context.close();
});
