import {test,expect} from './fixtures';
import {installAuthenticator} from './authenticator';
test('ADMIN確認・キャンセル・契約終了 → 実署名Passkey拒否、OWNER案件ARCHIVE、VersionとProof保持',async({page,browser})=>{
 test.setTimeout(120000);const headers={Origin:'http://localhost:8791'};
 await page.goto('/setup');await page.getByLabel('ユーザーID').fill('11111111-1111-4111-8111-111111111111');await page.getByLabel('初期設定トークン').fill('e2e-operator-only');await page.getByRole('button',{name:'登録する'}).click();await expect(page).toHaveURL(/\/settings\/security$/);
 // Register an ADMIN Passkey so the existing project-invite acceptance path can be used.
 await installAuthenticator(page);await page.reload();const registered=page.waitForResponse(r=>r.url().endsWith('/api/auth/passkey/register/verify')&&r.request().method()==='POST');await page.getByRole('button',{name:'パスキーを追加',exact:true}).click();expect((await registered).status()).toBe(200);await page.waitForLoadState('networkidle');
 await page.goto('/admin/users');const email=`termination-${Date.now()}@example.com`;await page.getByLabel('メール',{exact:true}).fill(email);await page.getByRole('button',{name:'利用開始URLを発行'}).click();const field=page.getByLabel('利用開始URL',{exact:true});await expect(field).toHaveValue(/\/activate\//);const url=await field.inputValue();
 const context=await browser.newContext({extraHTTPHeaders:{'CF-Connecting-IP':'e2e-terminated-owner'},viewport:{width:390,height:844}});const owner=await context.newPage(),auth=await installAuthenticator(owner);
 await owner.goto(url);await owner.getByLabel('表示名',{exact:true}).fill('契約終了対象');await owner.getByRole('button',{name:'Passkeyを登録して利用開始'}).click();await expect(owner.getByRole('heading',{name:'利用開始登録が完了しました'})).toBeVisible();await owner.getByRole('link',{name:'Creator Traceを開く'}).click();await owner.getByLabel('案件名',{exact:true}).fill('契約終了後も保持する案件');await owner.getByRole('button',{name:'登録する',exact:true}).click();await expect(owner.getByRole('heading',{name:'契約終了後も保持する案件',exact:true})).toBeVisible();
 const projectId=new URL(owner.url()).pathname.split('/').at(-1)!;const session=await (await owner.request.get('/api/auth/session')).json();
 const assetResponse=await owner.request.post(`/api/projects/${projectId}/assets`,{headers,data:{filename:'retained.txt',size:3,sha256:'a'.repeat(64),status:'SUBMITTED'}});expect(assetResponse.status()).toBe(201);const asset=await assetResponse.json();
 const proofBefore=await (await owner.request.get(`/api/proofs/${asset.proof_id}`)).json();const key=await (await owner.request.post('/api/api-keys',{headers,data:{name:'Termination test',scopes:['projects:read']}})).json();
 const invitation=await (await owner.request.post(`/api/projects/${projectId}/invites`,{headers,data:{email:'admin-review@example.com',role:'MANAGER'}})).json();expect((await page.request.post('/api/project-invites/accept',{headers,data:{token:invitation.url.split('/').at(-1)}})).status()).toBe(200);
 await page.goto('/admin/users');const card=page.locator('section.card').filter({hasText:email}).filter({has:page.getByRole('button',{name:'契約を終了する',exact:true})});await card.getByRole('button',{name:'契約を終了する'}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByText('過去の制作・承認・納品・証跡は削除されません',{exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'キャンセル'})).toBeFocused();
 for(const width of [1440,390]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await dialog.getByRole('button',{name:'キャンセル'}).click();expect((await owner.request.get(`/api/projects/${projectId}`)).status()).toBe(200);
 await card.getByRole('button',{name:'契約を終了する'}).click();await dialog.getByLabel('理由').fill('説明会後の契約終了テスト');await dialog.getByRole('button',{name:'契約を終了する',exact:true}).click();await expect(page.getByText('契約を終了しました。過去の履歴と証跡は保持しています。',{exact:true})).toBeVisible();const ended=page.locator('section.card').filter({hasText:email}).filter({hasText:'TERMINATED'});await expect(ended.getByText('契約終了済み',{exact:true})).toBeVisible();await expect(ended.getByRole('button',{name:'契約を終了する'})).toHaveCount(0);
 expect((await owner.request.get('/api/projects')).status()).toBe(401);expect((await owner.request.get('/api/v1/projects',{headers:{Authorization:`Bearer ${key.key}`}})).status()).toBe(401);
 const archived=await (await page.request.get(`/api/projects/${projectId}`)).json();expect(archived.archived_at).toBeTruthy();const members=await (await page.request.get(`/api/projects/${projectId}/members`)).json();expect(members.find((m:{user_id:string})=>m.user_id===session.recipient_id)).toMatchObject({role:'OWNER',status:'ACTIVE'});
 expect(await (await page.request.get(`/api/proofs/${asset.proof_id}`)).json()).toEqual(proofBefore);const retainedVersion=await page.request.get(`/api/assets/${asset.id}/versions/${asset.version_id}`);expect(retainedVersion.status()).toBe(200);expect(await retainedVersion.json()).toMatchObject({id:asset.version_id,sha256:'a'.repeat(64)});
 await owner.goto('/login');const rejected=owner.waitForResponse(r=>r.url().endsWith('/api/auth/passkey/login/verify'));await owner.getByRole('button',{name:'パスキーでログイン'}).click();expect((await rejected).status()).toBe(400);await expect(owner.getByText('Passkeyの確認に失敗しました。もう一度お試しください',{exact:true})).toBeVisible();await expect.poll(()=>auth.calls.map(c=>c.kind)).toEqual(['create','get']);await expect.poll(async()=>await (await owner.request.get('/api/auth/session')).json()).toEqual({authenticated:false});await expect(owner).toHaveURL(/\/login$/);
 await context.close();
});
