import './style.css';
import {startAuthentication,startRegistration} from '@simplewebauthn/browser';
import {digest} from './hash';
type Row=Record<string,any>;
const root=document.querySelector<HTMLDivElement>('#app')!;
root.innerHTML='<header><a class="brand" href="/">Creator <strong>Trace</strong></a><nav><a href="/projects">案件</a><a href="/assets">制作物</a><a href="/settings/security">認証設定</a></nav><div class="account-status" id="account-status"></div></header><main id="content" aria-live="polite"></main><footer>制作物の履歴と納品証跡を、安全に管理。</footer>';
const main=document.querySelector<HTMLElement>('#content')!;
function el(tag:string,text?:string,cls?:string){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;}
function link(text:string,url:string){const n=el('a',text) as HTMLAnchorElement;n.href=url;return n;}
const roleNames:Record<string,string>={OWNER:'Owner',MANAGER:'Manager',CREATOR:'Creator',REVIEWER:'Reviewer',VIEWER:'Viewer',APPROVER:'Approver'};
let loginSession:Row|undefined;
function showLoginUser(){const header=document.querySelector<HTMLElement>('#account-status')!;header.replaceChildren();if(!loginSession?.authenticated)return;header.append(el('span',`ログイン中：${loginSession.display_name||'表示名未設定'}${loginSession.is_admin?' / ADMIN':''}`));const logout=el('button','ログアウト') as HTMLButtonElement;logout.onclick=async()=>{logout.disabled=true;try{await api('/api/auth/logout',{});location.assign('/login');}catch(e){error(e);logout.disabled=false;}};header.append(logout);}
class APIError extends Error{status:number;constructor(status:number,message:string){super(message);this.status=status;}}
function inviteError(e:unknown){if(e instanceof APIError){return ({400:'入力内容を確認してください',403:'この案件ではメンバーを招待できません',409:'このメールアドレスには既に招待を送っています',410:'招待URLの有効期限が切れています',500:'招待の作成に失敗しました'} as Record<number,string>)[e.status]??e.message;}return e instanceof Error?e.message:'招待の作成に失敗しました';}
async function api<T=Row>(url:string,body?:unknown,method='POST'):Promise<T>{const r=await fetch(url,{credentials:'same-origin',...(body!==undefined?{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok){if(r.status===401)main.append(link('ログインする','/login'));throw new APIError(r.status,d.error??'通信に失敗しました');}return d;}
function error(e:unknown){main.append(el('p',e instanceof Error?e.message:'処理に失敗しました','error'));}
function field(form:HTMLElement,label:string,name:string,type='text',required=false){const l=el('label',label),i=document.createElement('input');i.name=name;i.type=type;i.required=required;if(type==='text')i.maxLength=200;l.append(i);form.append(l);return i;}
function form(title:string,submit:(data:FormData)=>Promise<void>){const f=document.createElement('form');f.append(el('h2',title));const b=el('button','登録する') as HTMLButtonElement;b.type='submit';f.onsubmit=async e=>{e.preventDefault();if(b.disabled)return;b.disabled=true;try{await submit(new FormData(f));}catch(e){error(e);}finally{b.disabled=false;}};f.append(b);main.append(f);return f;}
function text(d:FormData,key:string){return String(d.get(key)??'');}
function dt(value:unknown){return value?new Date(String(value)).toLocaleString('ja-JP'):'—';}
function details(fields:[string,unknown][]){const d=el('dl');for(const [k,v]of fields)d.append(el('dt',k),el('dd',String(v??'—')));return d;}
function list(rows:Row[],prefix:string,label:string){if(!rows.length)main.append(el('p','まだ登録されていません。','muted'));for(const row of rows){const card=el('section',undefined,'card');card.append(link(String(row[label]),`${prefix}/${encodeURIComponent(row.id)}`));if(row.latest_version)card.append(el('p',`最新Version：Version ${row.latest_version}`));if(row.latest_filename)card.append(el('p',`最新版ファイル：${row.latest_filename}`));if(row.client_name)card.append(el('p',row.client_name));if(row.project_name)card.append(el('p',row.project_name));main.append(card);}}
function fileForm(projectId:string,creators:Row[],assetId?:string){
 const f=form(assetId?'修正版を登録':'新しい制作物を登録',async d=>{const file=d.get('file');if(!(file instanceof File)||!file.name)throw new Error('ファイルを選択してください');const message=el('p','SHA-256を計算しています…','muted');f.append(message);try{const hash=await digest(file,p=>message.textContent=`Hashing ${p}%`);const result=await api(assetId?`/api/assets/${assetId}/versions`:`/api/projects/${projectId}/assets`,{...(!assetId?{name:text(d,'name')}:{ }),filename:file.name,mime_type:file.type||'application/octet-stream',size:file.size,sha256:hash,creator_id:text(d,'creator_id')||null,comment:text(d,'comment'),status:text(d,'status'),external_source_url:text(d,'external_source_url')||null});location.assign(`/assets/${assetId??result.id}`);}finally{message.remove();}});
 (f.querySelector('button') as HTMLButtonElement).textContent=assetId?'修正版を登録':'新しい制作物を登録';if(!assetId){field(f,'制作物名','name','text',true);f.append(el('p','同じ制作物の修正は、制作物詳細の「修正版を登録」から追加してください。','muted'));}field(f,'ファイル','file','file',true);field(f,'原本の外部保存先URL（資格情報・クエリなし）','external_source_url','url');const label=el('label','制作者'),select=document.createElement('select');select.name='creator_id';select.setAttribute('aria-label','制作者');const empty=new Option('案件所有者（制作者指定なし）','');select.add(empty);for(const c of creators)select.add(new Option(`${c.name} / ${c.role}`,c.id));label.append(select);f.append(label);
 const comment=field(f,'変更内容・納品コメント','comment');comment.maxLength=4000;
 const statusLabel=el('label','登録状態'),status=document.createElement('select');status.name='status';status.add(new Option('提出済み（SUBMITTED）','SUBMITTED'));status.add(new Option('下書き（DRAFT）','DRAFT'));statusLabel.append(status);f.append(statusLabel,el('p','ファイル本体は送信・保存しません。原本はDrive等で保管してください。SHA-256とファイル情報を登録します。大容量ファイルも端末内で分割して計算します。','muted'));
 return f;
}
function proofDate(value:unknown){if(!value)return '—';const date=new Date(String(value));if(Number.isNaN(date.valueOf()))return '日時の記録を確認できません';return new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(date)+' JST（UTC+09:00）';}
async function proofCard(p:Row){
 const c=el('section',undefined,'card');c.append(el('h2','Creator Trace Proof'),details([['ファイルの識別値（SHA-256）',p.sha256],['ファイル登録日時',proofDate(p.created_at)]]));main.append(c);
 main.append(el('h3','① 手元のファイルと登録ファイルの照合'),el('p','ファイル名ではなく、ファイル内容から計算したSHA-256を比較します。選択したファイルはブラウザー内で処理し、アップロードしません。'));
 const f=form('手元のファイルと照合',async d=>{const file=d.get('file');if(!(file instanceof File)||!file.name)throw new Error('ファイルを選択してください');const progress=el('p','SHA-256を計算しています…');result.textContent='';fileInput.disabled=true;f.append(progress);try{const match=await digest(file,percent=>progress.textContent=`SHA-256を計算しています… ${percent}%`)===p.sha256;result.textContent=match?'SHA-256が一致しました。同じ内容のファイルです。':'SHA-256が一致しません。ファイル内容が異なります。';}finally{progress.remove();fileInput.disabled=false;}});const fileInput=field(f,'確認するファイル','file','file',true);fileInput.onchange=()=>{result.textContent='';};const result=el('p');result.setAttribute('role','status');f.append(result);(f.querySelector('button') as HTMLButtonElement).textContent='ファイルを照合する';
}
function bitcoinProofCard(p:Row,withFileCheck=true){
 const states:Record<string,[string,string]>={
  BITCOIN_VERIFIED:['確認済み',p.bitcoin_confirmed_at?'Creator TraceでBitcoinの証明を検証済みです。':'Bitcoinの証明は確認済みですが、確認日時の記録はありません。'],
  BITCOIN_ANCHOR_FOUND:['Bitcoinアンカー情報あり・チェーン検証未実施',p.verification?.api_configured?'証跡にBitcoinブロックの情報があります。「Bitcoinを再確認」でチェーンとの一致を確認してください。':'証跡にBitcoinブロックの情報はありますが、チェーンとの照合はまだ行っていません。管理者がBitcoin API接続先を設定した後に「Bitcoinを再確認」を実行してください。'],
  VERIFY_FAILED:[p.verification?.has_ots?'再確認に失敗（作成済み証跡は保持）':'外部タイムスタンプの作成に失敗','前回の証跡作成・更新またはBitcoin検証に失敗しました。日時がないことだけでは確認待ちとは判断できません。設定・接続を確認し、再確認してください。'],
  RECEIPT_INVALID:['未確認（証跡を読み取れません）','保存された証跡を正しく読み取れません。管理者へお問い合わせください。'],
  NOT_REQUESTED:['未実行','外部タイムスタンプの作成・Bitcoin確認はまだ実行されていません。案件のOWNERまたはMANAGERが「証跡を作成 / 再確認」を実行してください。'],
  WAITING_BITCOIN:['未確認（Bitcoin情報の取得待ち）','外部タイムスタンプの証跡は作成済みですが、Bitcoinブロックの証明はまだ取得できていません。時間をおいて再確認してください。'],
  OTS_CREATED:['外部タイムスタンプ作成済み','外部タイムスタンプは作成済みです。Bitcoinブロックの情報はまだ取得できていません。'],
  UNKNOWN:['未確認（状態不明）','保存されている情報だけでは未実行・確認待ち・失敗を区別できません。案件の管理者に確認してください。']
 };
 const state=p.verification?.state??'UNKNOWN',[label,message]=states[state]??states.UNKNOWN;
 const timestamp=p.timestamp_created_at?'作成済み':state==='NOT_REQUESTED'?'未実行':state==='VERIFY_FAILED'&&!p.verification?.has_ots?'作成失敗':'未確認';
 const proof=el('section',undefined,'card proof-verification');proof.append(el('h3',withFileCheck?'② 証跡のBitcoin確認':'証跡のBitcoin確認'),details([['外部タイムスタンプ',timestamp],['外部タイムスタンプ作成日時',proofDate(p.timestamp_created_at)],['Bitcoin確認状態',label],['Bitcoin確認日時',proofDate(p.bitcoin_confirmed_at)],['Bitcoinブロック高さ',p.bitcoin_block_height??p.bitcoin_block??p.verification?.anchors?.[0]?.height??'—'],['Bitcoinブロックハッシュ',p.bitcoin_block_hash??'—'],['Bitcoinブロック採掘日時',proofDate(p.bitcoin_block_time)],['最終確認処理日時',proofDate(p.verification?.last_attempt?.checked_at??p.verification?.last_checked_at)]]),el('p',message),el('p','手元のファイルとの一致と、Bitcoin確認は別の確認です。SHA-256が一致しても、Bitcoinの証明が確認済みとは限りません。','muted'),el('p','外部タイムスタンプ作成日時は、外部サービスから証跡を受け取りCreator Traceに保存した日時です。同じSHA-256の既存証跡を使う場合は、その作成日時を引き継ぎます。Bitcoin確認日時はCreator Traceで検証に成功した日時で、ブロックの採掘日時ではありません。日時はすべて日本時間（JST・UTC+09:00）です。','muted'));
 if(p.verification?.last_attempt?.state==='VERIFY_FAILED')proof.append(el('p','直近のBitcoin再確認は失敗しました。作成済みの証跡と過去の確認結果は保持しています。接続先やブロック情報を確認し、時間をおいて再確認してください。'));
 main.append(proof);
}
function proofControls(p:Row,parent:HTMLElement,role?:string){if(!['OWNER','MANAGER'].includes(role??''))return;if(p.verification?.state!=='BITCOIN_VERIFIED')actionButton('証跡を作成 / 再確認',`/api/proofs/${p.id}/retry`,parent);if(p.verification?.has_ots)actionButton('Bitcoinを再確認',`/api/proofs/${p.id}/bitcoin-recheck`,parent);parent.append(el('p','再確認は60秒以上あけて実行してください。Bitcoinの確認には時間がかかる場合があります。','muted'));}
function pagedURL(path:string){const params=new URLSearchParams(location.search);params.set('pagination','1');return `${path}?${params}`;}
function versionURL(assetId:string,versionId:string){return `/assets/${encodeURIComponent(assetId)}/versions/${encodeURIComponent(versionId)}`;}
function breadcrumbs(items:[string,string?][]){const nav=el('nav',undefined,'breadcrumbs');nav.setAttribute('aria-label','パンくず');for(const [index,[label,url]]of items.entries()){if(index)nav.append(el('span','＞'));const item=url?link(label,url):el('span',label);if(!url)item.setAttribute('aria-current','page');nav.append(item);}main.append(nav);}
async function versionCard(v:Row,assetId:string,projectId:string,role:string,latest=false,showProof=false){const c=el('section',undefined,'card');c.append(el('h3',`Version ${v.version}${latest?' ・最新版':''}`),details([['状態',v.status],['ファイル名',v.filename],['サイズ',`${v.size} bytes`],['MIME type',v.mime_type],['制作者',v.creator_name||'案件所有者'],['登録日時',dt(v.created_at)],['SHA-256',v.sha256],['変更内容',v.comment||'—'],['外部証跡',v.timestamp_status==='CONFIRMED'?'確認済み':v.timestamp_status==='NOT_REQUESTED'?'未実行':'Bitcoin未確認（詳細は証跡詳細へ）']]),link('Version詳細',versionURL(assetId,v.id)),link('証跡詳細',`/proof/${v.proof_id}`));main.append(c);await versionControls(v,c,role,projectId);if(showProof){const proof=await api(`/api/proofs/${encodeURIComponent(v.proof_id)}`);bitcoinProofCard(proof,false);const actions=el('div',undefined,'history-actions');main.append(actions);proofControls(proof,actions,role);}}
const inviteStatuses:Record<string,string>={PENDING:'招待中',ACCEPTED:'参加済み',EXPIRED:'期限切れ',REVOKED:'無効'};
function actionButton(label:string,path:string,parent:HTMLElement=main,body:unknown={}){const b=el('button',label) as HTMLButtonElement;b.onclick=async()=>{b.disabled=true;try{await api(path,body);location.reload();}catch(e){error(e);}finally{b.disabled=false;}};parent.append(b);}
function archiveControl(path:string,parent:HTMLElement=main){actionButton('アーカイブする',path,parent);}
function searchPaging(hasNext:boolean,currentPage:number){const f=document.createElement('form');f.method='GET';const q=field(f,'検索','q');q.value=new URLSearchParams(location.search).get('q')??'';const b=el('button','検索') as HTMLButtonElement;f.append(b);main.append(f);const actions=el('div',undefined,'history-actions'),paging=el('nav',undefined,'pagination-actions');paging.setAttribute('aria-label','ページ切り替え');const page=currentPage;for(const n of [page-1,page+1])if(n>0&&(n<page||hasNext)){const params=new URLSearchParams(location.search);params.set('page',String(n));const a=link(n<page?'前へ':'次へ',`${location.pathname}?${params}`);a.className='button-link';paging.append(a);}if(paging.childElementCount)actions.append(paging);main.append(actions);return actions;}

async function botReviewControls(v:Row,parent:HTMLElement,projectId:string,role:string){
 const section=el('section',undefined,'ai-reviews'),button=el('button','5人のBotでレビューする') as HTMLButtonElement,results=el('div'),notice=el('p');
 section.append(el('h4','AI制作レビュー'),el('p',`対象Version：Version ${v.version}`),el('p',`現在状態：${v.status}`),el('p','AIレビューは参考情報です。状態の変更はお客様が行います。','muted'),button,notice,results);parent.append(section);if(role==='VIEWER')button.remove();
 let poll:ReturnType<typeof setTimeout>|undefined;
 const path=`/api/projects/${projectId}/bot-reviews`,failure='AIレビューに失敗しました。制作データには変更ありません。';
 function show(runs:Row[]){if(poll)clearTimeout(poll);results.replaceChildren();let running=false;for(const run of runs.slice(0,1)){const group=el('details') as HTMLDetailsElement;group.open=true;group.append(el('summary',`レビュー ${dt(run.created_at)} / ${run.status}`));if(run.status==='RUNNING'){running=true;group.append(el('p','AIレビュー中...'));}if(run.status==='FAILED')group.append(el('p',failure,'error'));for(const message of run.messages??[]){group.append(el('h5',message.bot_name),el('p',message.role),el('p',message.content,'review-content'));}results.append(group);}button.disabled=running;button.textContent=running?'AIレビュー中...':'5人のBotでレビューする';if(running)poll=setTimeout(()=>{if(section.isConnected)void reload().catch(()=>{notice.textContent='レビュー履歴を取得できませんでした。再読み込みしてください。';});},4000);}
 async function reload(){show(await api<Row[]>(`${path}?assetVersionId=${encodeURIComponent(v.id)}`));}
 button.onclick=async()=>{button.disabled=true;button.textContent='AIレビュー中...';notice.textContent='';try{await api(path,{assetVersionId:v.id});await reload();}catch(e){notice.textContent=e instanceof Error?e.message:failure;notice.className='error';try{await reload();}catch{button.disabled=false;button.textContent='5人のBotでレビューする';}}};
 try{await reload();}catch(e){notice.textContent=e instanceof Error?e.message:'レビュー履歴を取得できませんでした';notice.className='error';}
}
async function versionControls(v:Row,parent:HTMLElement,role:string,projectId:string){
 await botReviewControls(v,parent,projectId,role);
 const people=await api<Row[]>(`/api/projects/${projectId}/members`);const person=(id:string)=>{const member=people.find(m=>m.user_id===id);return member?`${member.display_name||'表示名未設定'}${member.status==='ACTIVE'?'':'（現在は案件メンバーではありません）'}`:'未確認';};parent.append(el('p',`登録者：${person(v.created_by)}`));
 const history=await api(`/api/asset-versions/${v.id}/history`);for(const h of history.history)parent.append(el('p',`${h.from_status??'登録'} → ${h.to_status} / ${dt(h.created_at)} / ${person(h.actor_user_id)} / ${h.actor_role??'当時のRole未確認'} / ${h.reason}`));for(const approval of history.approvals)parent.append(el('p',`承認履歴 ${approval.decision} / ${person(approval.approver_user_id)} / ${approval.approver_role??'当時のRole未確認'} / ${dt(approval.created_at)} / ${approval.comment}`));
 const transitions:Record<string,[string,string][]>= {DRAFT:[['提出する','submit']],SUBMITTED:[['承認する','approve'],['差し戻す','reject']],APPROVED:[['FINALに確定','finalize']]};
 for(const [label,action]of transitions[v.status]??[]){if(!(['approve','reject'].includes(action)?['OWNER','MANAGER','REVIEWER']:action==='submit'?['OWNER','MANAGER','CREATOR']:['OWNER']).includes(role))continue;const f=document.createElement('form');const reason=field(f,action==='approve'?'承認コメント（任意）':action==='reject'?'差戻しコメント':'理由・コメント','reason','text',action==='reject');reason.maxLength=4000;const b=el('button',label) as HTMLButtonElement;f.append(b);f.onsubmit=async e=>{e.preventDefault();b.disabled=true;try{await api(`/api/asset-versions/${v.id}/${action}`,['approve','reject'].includes(action)?{comment:reason.value}:{reason:reason.value});location.reload();}catch(e){error(e);}finally{b.disabled=false;}};parent.append(f);}
 if(v.external_source_url)parent.append(link('原本の保存先を開く',v.external_source_url));
 const deliveries=await api<Row[]>(`/api/asset-versions/${v.id}/deliveries`);for(const d of deliveries){parent.append(el('p',`納品 ${dt(d.delivered_at)} / ${d.receipt_status} / 受領 ${dt(d.received_at)} / 納品者：${person(d.delivered_by)} / 受領者：${person(d.recipient_user_id)}`));if(d.receipt_status==='DELIVERED'&&role!=='VIEWER'&&d.recipient_user_id===loginSession?.recipient_id){actionButton('受領する',`/api/deliveries/${d.id}/receive`,parent);actionButton('受領差戻し',`/api/deliveries/${d.id}/reject`,parent);}}
 if(v.status==='FINAL'&&['OWNER','MANAGER','APPROVER'].includes(role)){
  const members=(await api<Row[]>(`/api/projects/${projectId}/members`)).filter(m=>m.status==='ACTIVE');
  if(!members.length){parent.append(el('p','この案件には受領者として選択できるメンバーがいません','muted'));return;}
  const f=document.createElement('form'),label=el('label','受領者'),select=document.createElement('select');select.name='recipient_user_id';select.required=true;
  select.add(new Option('受領者を選択してください',''));for(const member of members)select.add(new Option(member.display_name||'表示名未設定',member.user_id));
  select.oninvalid=()=>select.setCustomValidity('受領者を選択してください');select.onchange=()=>select.setCustomValidity('');label.append(select);f.append(label);
  field(f,'納品コメント','comment').maxLength=4000;const button=el('button','納品を記録') as HTMLButtonElement;f.append(button);
  f.onsubmit=async e=>{e.preventDefault();button.disabled=true;try{const data=new FormData(f);if(!text(data,'recipient_user_id'))throw new Error('受領者を選択してください');await api(`/api/asset-versions/${v.id}/deliveries`,{recipient_user_id:text(data,'recipient_user_id'),comment:text(data,'comment')});location.reload();}catch(e){error(e);}finally{button.disabled=false;}};parent.append(f);
 }
}
async function reviewerComments(assetId:string,versions:Row[],role:string){
 const section=el('section',undefined,'reviewer-comments');section.append(el('h2','Reviewerコメント'));main.append(section);const history=el('div');history.setAttribute('aria-label','Reviewerコメント履歴');
 async function reload(){const rows=await api<Row[]>(`/api/assets/${assetId}/review-comments`);history.replaceChildren(el('h3','コメント履歴'));if(!rows.length)history.append(el('p','コメントはまだありません','muted'));for(const row of rows){const entry=el('article',undefined,'card');entry.append(el('p',dt(row.created_at)),el('p',`${row.reviewer_name}${row.reviewer_removed?'（現在は案件メンバーではありません）':''}`),link(`v${row.version}`,versionURL(assetId,row.version_id)),el('p',row.comment,'review-content'));history.append(entry);}}
 if(role==='REVIEWER'&&versions.length){const f=document.createElement('form'),label=el('label','コメント投稿時点のVersion'),select=document.createElement('select');select.name='version_id';for(const v of versions)select.add(new Option(`v${v.version}`,v.id));label.append(select);const commentLabel=el('label','コメント'),input=document.createElement('textarea');input.name='comment';input.required=true;input.maxLength=4000;input.rows=4;commentLabel.append(input);const button=el('button','コメントを追加') as HTMLButtonElement;button.type='submit';const notice=el('p');notice.setAttribute('role','status');f.append(label,commentLabel,button,notice);f.onsubmit=async e=>{e.preventDefault();if(button.disabled)return;if(!input.value.trim()){notice.textContent='コメントを入力してください';return;}button.disabled=true;try{await api(`/api/assets/${assetId}/review-comments`,{version_id:select.value,comment:input.value});input.value='';await reload();notice.textContent='コメントを追加しました';}catch(e){notice.textContent=e instanceof Error?e.message:'コメントの登録に失敗しました';}finally{button.disabled=false;}};section.append(f);}
 section.append(history);await reload();
}
async function projectControls(p:Row){
 main.append(el('h2','案件メンバー'));const roster=el('div');main.append(roster);
 const members=await api<Row[]>(`/api/projects/${p.id}/members`),canInvite=['OWNER','MANAGER'].includes(p.current_role);
 function renderMembers(){roster.replaceChildren();const table=el('table'),head=el('tr');for(const title of ['表示名','Role','状態','参加日時','操作'])head.append(el('th',title));table.append(head);
  for(const member of members.filter(m=>m.status==='ACTIVE')){const row=el('tr');for(const value of [member.display_name||'表示名未設定',member.role,'参加済み',dt(member.joined_at)])row.append(el('td',value));const actions=el('td');

   if(p.current_role==='OWNER'&&member.role!=='OWNER'){const button=el('button','メンバーを外す') as HTMLButtonElement;button.onclick=()=>{
    const dialog=document.createElement('dialog');dialog.append(el('h3',`${member.display_name||'このメンバー'} をこの案件から外しますか？`),el('p','過去の制作・納品・承認履歴は残りますが、今後この案件へアクセスできなくなります。'));
    const cancel=el('button','キャンセル') as HTMLButtonElement,confirm=el('button','メンバーを外す') as HTMLButtonElement;cancel.onclick=()=>{dialog.close();dialog.remove();};confirm.onclick=async()=>{if(confirm.disabled)return;confirm.disabled=true;cancel.disabled=true;try{await api(`/api/projects/${p.id}/members/${member.id}/remove`,{});location.reload();}catch(e){dialog.append(el('p',e instanceof Error?e.message:'メンバーを外せませんでした','error'));confirm.disabled=false;cancel.disabled=false;}};dialog.append(cancel,confirm);dialog.addEventListener('close',()=>dialog.remove());main.append(dialog);dialog.showModal();
   };actions.append(button);}else actions.textContent='—';row.append(actions);table.append(row);
  }roster.append(table);
  const past=members.flatMap(member=>(member.history??[]).filter((h:Row)=>h.status==='REMOVED'||h.status==='REVOKED').map((h:Row)=>({member,h})));if(past.length){const section=el('details');section.append(el('summary','過去のメンバー・取消履歴'));for(const {member,h} of past){section.append(el('p',`${member.display_name||'表示名未設定'} / ${h.role} / 参加：${dt(h.joined_at)} / 取消：${dt(h.removed_at)} / 取消者：${h.removed_by_name||'未確認'}${member.status==='ACTIVE'?' / 現在は再参加済み':'（現在は案件メンバーではありません）'}`));}roster.append(section);}
 }

 renderMembers();if(!canInvite)return;
 const pendingList=el('div'),inviteHistory=el('div');inviteHistory.className='invite-history';main.append(el('h2','招待中'),pendingList,el('h2','招待履歴（最新3件）'),inviteHistory);
 async function refreshInvites(){const [invites,pending]=await Promise.all([api<Row[]>(`/api/projects/${p.id}/invites?limit=3`),api<Row[]>(`/api/projects/${p.id}/invites?status=PENDING`)]);renderMembers();pendingList.replaceChildren();const table=el('table'),head=el('tr');for(const title of ['メール','Role','状態','作成日時'])head.append(el('th',title));table.append(head);for(const item of pending){const row=el('tr');for(const value of [item.email,item.role,'招待中 (PENDING)',dt(item.created_at)])row.append(el('td',value));table.append(row);}pendingList.append(table);inviteHistory.replaceChildren();for(const item of invites){const card=el('div',undefined,'invite-record');card.append(details([['招待先',item.email],['Role',item.role],['招待状態',`${inviteStatuses[item.status]} (${item.status})`],['作成日時',dt(item.created_at)],['有効期限',dt(item.expires_at)]]));if(item.status==='PENDING'){const cancel=el('button','招待を取り消す') as HTMLButtonElement;cancel.onclick=async()=>{cancel.disabled=true;try{await api(`/api/projects/${p.id}/invites/${item.id}/revoke`,{});await refreshInvites();}catch(e){error(e);cancel.disabled=false;}};card.append(cancel);}inviteHistory.append(card);}if(!invites.length)inviteHistory.append(el('p','招待はありません','muted'));}
 await refreshInvites();const inviteResult=el('div');
 const invite=form('案件メンバーを招待',async d=>{
  inviteButton.textContent='招待作成中...';inviteResult.replaceChildren();
  try{const email=text(d,'email'),role=text(d,'role'),result=await api(`/api/projects/${p.id}/invites`,{email,role});
   if(typeof result.id!=='string'||typeof result.url!=='string')throw new Error('招待の作成結果を確認できませんでした');
   inviteResult.append(el('p','招待を作成しました'),details([['招待ID',result.id],['招待先',result.email??email],['Role',result.role??role],['招待状態',`${inviteStatuses[result.status??'PENDING']} (${result.status??'PENDING'})`],['作成日時',dt(result.created_at)]]),el('p','メールは自動送信されません。このURLを招待先へ共有してください。URLは作成直後のみ表示します。'));
   const url=field(inviteResult,'招待URL','invite_url');url.value=result.url;url.readOnly=true;const copy=el('button','招待URLをコピー') as HTMLButtonElement;copy.type='button';const notice=el('p');copy.onclick=async()=>{try{await navigator.clipboard.writeText(result.url);notice.textContent='コピーしました';}catch{url.focus();url.select();notice.textContent='コピーできませんでした。選択したURLを手動でコピーしてください。';}};inviteResult.append(copy,notice);invite.reset();copy.focus();
   try{await refreshInvites();}catch{inviteResult.append(el('p','招待は作成済みです。招待一覧を更新できませんでした。','error'));}
  }catch(e){inviteResult.append(el('p',inviteError(e),'error'));}finally{inviteButton.textContent='メンバーを招待する';}
 });const inviteButton=invite.querySelector('button') as HTMLButtonElement;inviteButton.textContent='メンバーを招待する';field(invite,'招待先メール（連絡先）','email','email',true);const label=el('label','Role'),roles=document.createElement('select');roles.name='role';roles.setAttribute('aria-label','Role');for(const role of ['MANAGER','CREATOR','REVIEWER','VIEWER'])roles.add(new Option(role,role,role==='CREATOR',role==='CREATOR'));roles.value='CREATOR';label.append(roles);invite.append(label,el('p','OWNERは案件作成者のみです。','muted'));inviteResult.setAttribute('role','status');main.append(inviteResult);
 const edit=form('案件情報を編集',async d=>{await api(`/api/projects/${p.id}/edit`,{name:text(d,'name'),client_name:text(d,'client_name'),description:text(d,'description')});location.reload();});field(edit,'案件名','name','text',true).value=p.name;field(edit,'クライアント名','client_name').value=p.client_name;field(edit,'説明','description').value=p.description??'';archiveControl(`/api/projects/${p.id}/archive`);
 const log=el('details');log.append(el('summary','監査ログ'));for(const event of await api<Row[]>(`/api/projects/${p.id}/audit`))log.append(el('p',`${dt(event.created_at)} ${event.event_type}`));main.append(log);
}
const inquiryStatuses:Record<string,string>={NEW:'未対応',IN_PROGRESS:'対応中',COMPLETED:'完了'};
async function adminNavigation(){const response=await fetch('/api/admin/access',{credentials:'same-origin'});if(response.ok){const nav=document.querySelector('nav')!,settings=nav.querySelector('a[href="/settings/security"]');nav.insertBefore(link('問い合わせ','/admin/inquiries'),settings);nav.insertBefore(link('利用者管理','/admin/users'),settings);}}
async function render(){const path=location.pathname;let m:RegExpMatchArray|null;
 if(path==='/admin/users'){
  await api('/api/admin/users');main.append(el('h1','利用者管理'));
  const issued=el('section');issued.setAttribute('role','status');
  const rows=el('div');
  async function refresh(){const result=await api('/api/admin/users');rows.replaceChildren(el('h2','利用者一覧'));for(const user of result.users){const card=el('section',undefined,'card');card.append(details([['表示名',user.display_name],['メール',user.email],['状態',user.status],['システムRole',user.system_role],['登録日時',dt(user.created_at)]]));rows.append(card);}rows.append(el('h2','利用開始URLの発行履歴'));for(const row of result.activations){const card=el('section',undefined,'card');card.append(details([['メール',row.email],['状態',row.status],['発行日時',dt(row.created_at)],['有効期限',dt(row.expires_at)],['利用開始日時',dt(row.activated_at)]]));if(row.status==='PENDING'){const revoke=el('button','発行を取り消す') as HTMLButtonElement;revoke.onclick=async()=>{revoke.disabled=true;try{await api(`/api/admin/account-activations/${encodeURIComponent(row.id)}/revoke`,{});issued.replaceChildren();await refresh();}catch(e){error(e);}finally{revoke.disabled=false;}};card.append(revoke);}rows.append(card);}}
  const f=form('新しい利用者を発行',async d=>{issued.replaceChildren();const result=await api('/api/admin/account-activations',{email:text(d,'email')});issued.append(el('h2','利用開始URL'),el('p','このURLは作成直後だけ表示します。有効期限は7日間です。顧客へ手動でお渡しください。'));const input=field(issued,'利用開始URL','activation_url','url');input.value=result.url;input.readOnly=true;const copy=el('button','URLをコピー') as HTMLButtonElement;copy.type='button';const notice=el('p');copy.onclick=async()=>{try{await navigator.clipboard.writeText(result.url);notice.textContent='コピーしました';}catch{input.focus();input.select();notice.textContent='選択したURLを手動でコピーしてください。';}};issued.append(copy,notice);f.reset();await refresh();});field(f,'メール','email','email',true).maxLength=254;(f.querySelector('button') as HTMLButtonElement).textContent='利用開始URLを発行';main.append(issued,rows);await refresh();return;
 }
 if((m=path.match(/^\/activate\/([a-f0-9]{64})$/))){
  main.append(el('h1','Creator Trace 利用開始'));const token=m[1];
  let preview:Row;try{preview=await api('/api/auth/account-activation/preview',{token});}catch(e){error(e);return;}
  if(loginSession?.authenticated){main.append(el('p','利用開始はログアウトしてから行ってください。'));return;}
  main.append(details([['登録先',preview.email]]));
  const f=form('表示名を決めて利用開始',async d=>{const optionsJSON=await api<Parameters<typeof startRegistration>[0]['optionsJSON']>('/api/auth/passkey/register/options',{activationToken:token,display_name:text(d,'display_name')});const response=await startRegistration({optionsJSON});await api('/api/auth/passkey/register/verify',{response});loginSession=await api('/api/auth/session');showLoginUser();main.replaceChildren(el('h1','利用開始登録が完了しました'),details([['表示名',loginSession!.display_name]]),link('Creator Traceを開く','/projects'));});const name=field(f,'表示名','display_name','text',true);name.maxLength=50;name.pattern='.*\\S.*';(f.querySelector('button') as HTMLButtonElement).textContent='Passkeyを登録して利用開始';return;
 }
 if(path==='/admin/inquiries'){
  const rows=await api<Row[]>('/api/admin/inquiries');main.append(el('h1','問い合わせ'));
  if(!rows.length)main.append(el('p','問い合わせはありません','muted'));
  for(const row of rows){const card=el('section',undefined,'card');card.append(link(row.name,`/admin/inquiries/${encodeURIComponent(row.id)}`),details([['受付日時',dt(row.created_at)],['氏名',row.name],['会社',row.company],['メール',row.email],['チーム人数',row.team_size],['課題',row.problem],['ステータス',inquiryStatuses[row.status]??row.status]]));main.append(card);}return;
 }
 if((m=path.match(/^\/admin\/inquiries\/([^/]+)$/))){
  const row=await api(`/api/admin/inquiries/${encodeURIComponent(m[1])}`);main.append(el('h1','問い合わせ詳細'),link('問い合わせ一覧へ','/admin/inquiries'),details([['氏名',row.name],['会社',row.company],['メール',row.email],['チーム人数',row.team_size],['現在のツール',row.current_tools],['課題',row.problem],['メッセージ',row.message],['受付日時',dt(row.created_at)],['ステータス',inquiryStatuses[row.status]??row.status]]));
  for(const [label,status] of row.status==='NEW'?[['対応を開始','IN_PROGRESS'],['完了にする','COMPLETED']]:row.status==='IN_PROGRESS'?[['完了にする','COMPLETED']]:[]){const button=el('button',label) as HTMLButtonElement;button.onclick=async()=>{button.disabled=true;try{await api(`/api/admin/inquiries/${encodeURIComponent(row.id)}/status`,{status},'PATCH');location.reload();}catch(e){error(e);}finally{button.disabled=false;}};main.append(button);}return;
 }
 if((m=path.match(/^\/invite\/([A-Za-z0-9_-]+)\/signup$/))){
  const token=m[1],preview=await api('/api/project-invites/preview',{token});showLoginUser();main.append(el('h1','招待された案件へ参加'),details([['案件',preview.project_name],['招待先',preview.email],['Role',preview.role]]));
  if(preview.status!=='PENDING'||preview.project_archived_at){main.append(el('p',preview.status==='EXPIRED'?'招待URLの有効期限が切れています':'この招待では参加できません。','error'));return;}
  const session=await api('/api/auth/session');if(session.authenticated){location.assign(`/invite/${token}`);return;}
  main.append(el('p','初めてご利用の方は、新しいPasskeyを登録します。Windowsでスマホに保存する場合は「iPhone、iPad、またはAndroidデバイス」を選び、QRコードを読み取ってください。'));
  let registered=false;
  const f=form('新しいPasskeyを登録',async d=>{if(!registered){await api('/api/auth/invite-signup',{name:text(d,'name'),token});const optionsJSON=await api<Parameters<typeof startRegistration>[0]['optionsJSON']>('/api/auth/passkey/register/options',{});const response=await startRegistration({optionsJSON});await api('/api/auth/passkey/register/verify',{response});registered=true;name.readOnly=true;}const result=await api('/api/project-invites/accept',{token,display_name:text(d,'name')});location.assign(`/projects/${encodeURIComponent(result.project_id)}?joined=1`);});const name=field(f,'表示名','name','text',true);name.maxLength=50;name.pattern='.*\\S.*';(f.querySelector('button') as HTMLButtonElement).textContent='Passkeyを登録して参加する';main.append(link('登録済み：ログイン',`/login?invite=${encodeURIComponent(token)}`));return;
 }
 // Preserve old links without exposing a general registration form.
 if(path==='/signup'){location.replace('/login');return;}
 if((m=path.match(/^\/invite\/([A-Za-z0-9_-]+)$/))){main.append(el('h1','案件への招待'),el('p','初めてご利用の方はPasskeyを新しく登録してください。登録済みの方は、お持ちのPasskeyでログインしてください。この招待は一度だけ利用できます。'));
  const token=m[1],preview=await api('/api/project-invites/preview',{token});showLoginUser();main.append(el('h2','招待内容確認'),details([['案件',preview.project_name],['招待先',preview.email],['Role',preview.role],['招待状態',`${inviteStatuses[preview.status]} (${preview.status})`],['作成日時',dt(preview.created_at)],['有効期限',dt(preview.expires_at)]]));
  if(preview.status!=='PENDING'||preview.project_archived_at){main.append(el('p',preview.status==='EXPIRED'?'招待URLの有効期限が切れています':'この招待では参加できません。必要な場合は管理者へお問い合わせください。','error'));return;}
  const session=await api('/api/auth/session');if(!session.authenticated){main.append(link('初めての利用：Passkey登録',`${path}/signup`),link('登録済み：ログイン',`/login?invite=${encodeURIComponent(token)}`)); }else{
  const f=form('表示名を確認して参加',async d=>{const result=await api('/api/project-invites/accept',{token,display_name:text(d,'display_name')});if(loginSession){loginSession.display_name=result.display_name;loginSession.memberships=[...(loginSession.memberships??[]),{project_id:result.project_id,project_name:result.project_name,role:result.role}];showLoginUser();}main.replaceChildren(el('h1','案件への参加が完了しました'),details([['案件',result.project_name],['表示名',result.display_name],['Role',result.role]]),link('案件を開く',`/projects/${encodeURIComponent(result.project_id)}`));});const name=field(f,'表示名','display_name','text',true);name.value=session.display_name??'';name.maxLength=50;name.pattern='.*\\S.*';(f.querySelector('button') as HTMLButtonElement).textContent='案件へ参加する';f.append(el('p','表示名はアカウント全体に適用されます。','muted'));
 }return;
 }
 if(path==='/business'){
  main.append(el('h1','Creator Trace Business'),el('p','制作チームの導入についてご相談ください。'),el('p','送信後、内容を確認のうえご連絡します。この送信だけで契約・料金は発生しません。'));
  const f=form('導入について問い合わせる',async d=>{await api('/api/business/inquiries',Object.fromEntries(['name','company','email','team_size','current_tools','problem','message'].map(key=>[key,text(d,key)])));f.reset();main.append(el('p','お問い合わせを受け付けました。'));});(f.querySelector('button') as HTMLButtonElement).textContent='導入について問い合わせる';
  for(const [label,name,type,required] of [['氏名','name','text',true],['会社','company','text',false],['メール','email','email',true],['チーム人数','team_size','text',false],['現在のツール','current_tools','text',false],['課題','problem','text',false],['メッセージ','message','text',false]] as const){const input=field(f,label,name,type,required);input.maxLength=['problem','message'].includes(name)?4000:name==='current_tools'?1000:name==='team_size'?100:200;}return;
 }
 if(path==='/'){
  main.append(el('h1','Creator Trace'),el('h2','制作物の版と証跡を、案件ごとに残す'),el('p','ファイル本体はサーバーに置かず、ハッシュと版の履歴を残します。公開確認は、公開対象にした制作物だけです。'),link('案件を管理する','/projects'));
  const c=el('section',undefined,'card');c.append(el('h2','届いた版を、案件ごとに残す'),el('p','制作物ごとに、版と変更内容を残します。登録日時は版の詳細で見ます。'),el('p','登録したファイルと、手元のファイルのハッシュが同じかを確認できます。権利、作者、制作方法は証明しません。'));main.append(c);
  main.append(el('p','導入前のデータは記録できません。'));
  const services=el('section',undefined,'card');services.append(el('h2','制作チームの運用支援'),el('p','導入前の確認 無料：納品の流れ、原本の置き場、証跡の有無を見て、導入パックが要るかを提案。'),el('p','導入パック 121,500円 ＋ カスタマイズ費用'),el('p','カスタマイズ費用は、必要な機能・運用内容を確認したうえで個別に見積もります。'),el('p','保守は任意です。要る場合は32,000円です。導入時に決めます。'));main.append(services);
  const trial=el('section',undefined,'card');trial.append(el('h2','貸し出し・お試しについて'),el('p','貸し出しは、説明会のあとです。数ヶ月のお試しのあと、導入パックに進みます。'),el('p','月額は、説明会にて案内します。'),el('p','1ヶ月は無料です。ログインは、説明会のあとです。'));main.append(trial);
  main.append(link('ログイン','/login'),document.createTextNode('　'),link('導入について相談する','/business'));return;
 }
 if(path==='/setup'){main.append(el('h1','初回アカウント設定'),el('p','管理者が作成したユーザーIDと初期設定トークンを入力し、パスキーを登録してください。'));const f=form('管理者による初期設定',async d=>{const r=await fetch('/api/auth/owner-session',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${text(d,'token')}`},body:JSON.stringify({user_id:text(d,'user_id')})});if(!r.ok){const data=await r.json();throw new Error(data.error);}location.assign('/settings/security');});field(f,'ユーザーID','user_id','text',true);field(f,'初期設定トークン','token','password',true);return;}
 if(path==='/login'){const inviteToken=new URLSearchParams(location.search).get('invite');if(inviteToken){const preview=await api('/api/project-invites/preview',{token:inviteToken});main.append(details([['案件',preview.project_name],['招待先',preview.email],['Role',preview.role]]));if(preview.status!=='PENDING'||preview.project_archived_at){main.append(el('p',preview.status==='EXPIRED'?'招待URLの有効期限が切れています':'この招待では参加できません。','error'));return;}}main.append(el('h1','ログイン'),el('p','説明会のあと、渡したアカウントで入ります。'));const b=el('button','パスキーでログイン') as HTMLButtonElement;b.onclick=async()=>{b.disabled=true;try{const optionsJSON=await api<Parameters<typeof startAuthentication>[0]['optionsJSON']>('/api/auth/passkey/login/options',{});const response=await startAuthentication({optionsJSON});await api('/api/auth/passkey/login/verify',{response});location.assign(inviteToken?`/invite/${encodeURIComponent(inviteToken)}`:'/projects');}catch(e){error(e);}finally{b.disabled=false;}};main.append(b);if(inviteToken)main.append(link('初めての利用：Passkey登録',`/invite/${encodeURIComponent(inviteToken)}/signup`));return;}
 if(path==='/settings/security'){const session=await api('/api/auth/session');if(!session.authenticated){location.assign('/login');return;}main.append(el('h1','パスキー設定'));const keyName=field(main,'追加Passkeyの名前','passkey_name');keyName.value='Passkey';const keys=await api('/api/auth/passkeys');main.append(el('p',`登録済み：${keys.passkeys.length}件`));for(const key of keys.passkeys){main.append(el('p',`${key.name} / ${dt(key.created_at)}`));if(keys.passkeys.length>1)actionButton('このPasskeyを削除',`/api/auth/passkeys/${encodeURIComponent(key.id)}/remove`);}main.append(el('p','端末紛失に備えて別端末にもPasskeyを追加してください。'),link('APIキー設定','/settings/api-keys'));const b=el('button','パスキーを追加') as HTMLButtonElement;b.onclick=async()=>{b.disabled=true;try{const optionsJSON=await api<Parameters<typeof startRegistration>[0]['optionsJSON']>('/api/auth/passkey/register/options',{});const response=await startRegistration({optionsJSON});await api('/api/auth/passkey/register/verify',{response,name:keyName.value});location.reload();}catch(e){error(e);}finally{b.disabled=false;}};main.append(b);return;}
 if(path==='/projects'){const result=await api(pagedURL('/api/projects'));searchPaging(result.hasNext,result.page);main.append(el('h1','案件一覧'));const empty=result.items.length===0&&result.page===1&&!new URLSearchParams(location.search).get('q');if(empty)main.append(el('p','まだ案件がありません。'),link('最初の案件を作成','#new-project'));else list(result.items,'/projects','name');const f=form(empty?'最初の案件を作成':'案件を作成',async d=>{const item=await api('/api/projects',{name:text(d,'name'),client_name:text(d,'client_name'),start_date:text(d,'start_date')||null,end_date:text(d,'end_date')||null});location.assign(`/projects/${item.id}`);});f.id='new-project';field(f,'案件名','name','text',true);field(f,'クライアント名','client_name');field(f,'開始日','start_date','date');field(f,'終了日','end_date','date');return;}
 if((m=path.match(/^\/projects\/([^/]+)$/))){const p=await api(`/api/projects/${m[1]}${location.search}`);showLoginUser();if(new URLSearchParams(location.search).get('joined')==='1')main.append(el('p','案件への参加が完了しました'));breadcrumbs([['案件一覧','/projects'],[p.name]]);main.append(el('h1',p.name));const canRegister=['OWNER','MANAGER','CREATOR'].includes(p.current_role);if(canRegister){const anchor=link('新しい制作物を登録','#new-asset');anchor.className='button-link';main.append(anchor);}main.append(details([['クライアント',p.client_name||'—'],['この案件でのRole',roleNames[p.current_role]??p.current_role],['制作期間',`${p.start_date??'未定'} 〜 ${p.end_date??'未定'}`]]));if(p.creators.length){const legacy=el('details');legacy.append(el('summary','過去の担当者・制作者'));for(const c of p.creators)legacy.append(el('p',`${c.name} / ${c.role}`));main.append(legacy);}main.append(el('h2','制作物'));searchPaging(p.assets_pagination.hasNext,p.assets_pagination.page);list(p.assets,'/assets','name');await projectControls(p);if(canRegister){const section=el('section');section.id='new-asset';section.setAttribute('aria-label','新しい制作物を登録');section.append(fileForm(p.id,p.creators));main.append(section);}return;}
 if(path==='/assets'){const result=await api(pagedURL('/api/assets'));searchPaging(result.hasNext,result.page);main.append(el('h1','制作物一覧'));list(result.items,'/assets','name');main.append(link('案件から制作物を登録','/projects'));return;}
 if((m=path.match(/^\/assets\/([^/]+)\/versions\/([^/]+)$/))){const v=await api(`/api/assets/${m[1]}/versions/${m[2]}`),a=await api(`/api/assets/${m[1]}`),p=await api(`/api/projects/${a.project_id}`);showLoginUser();breadcrumbs([['案件',`/projects/${a.project_id}`],['制作物',`/assets/${a.id}`],[`Version ${v.version}`]]);main.append(el('h1',`Version ${v.version}`),link('← 制作物に戻る',`/assets/${a.id}`));await versionCard(v,a.id,a.project_id,p.current_role,false,true);await reviewerComments(a.id,[v],p.current_role);return;}
 if((m=path.match(/^\/assets\/([^/]+)$/))){const a=await api(`/api/assets/${m[1]}${location.search}`),p=await api(`/api/projects/${a.project_id}`);showLoginUser();breadcrumbs([['案件',`/projects/${a.project_id}`],['制作物']]);main.append(el('h1',a.name??a.filename),el('p',`最新Version：Version ${a.latest_version??'未確認'}`),el('p',`最新版ファイル：${a.latest_filename??'未確認'}`),link('案件へ',`/projects/${a.project_id}`),el('h2','バージョン履歴'));for(const v of a.versions)await versionCard(v,a.id,a.project_id,p.current_role,v.version===a.latest_version);await reviewerComments(a.id,a.versions,p.current_role);const actions=searchPaging(a.versions_pagination.hasNext,a.versions_pagination.page);if(['OWNER','MANAGER'].includes(p.current_role))archiveControl(`/api/assets/${a.id}/archive`,actions);if(['OWNER','MANAGER','CREATOR'].includes(p.current_role))fileForm(a.project_id,p.creators,a.id);return;}
 if((m=path.match(/^\/(proof|verify)\/([^/]+)(\/check)?$/))){main.append(el('h1',m[1]==='verify'?'公開確認':m[3]?'ファイルと証跡の確認':'証跡詳細'));const p=await api(`/api/${m[1]==='verify'?'verify':'proofs'}/${m[2]}`);if(m[1]==='proof'){showLoginUser();const back=versionURL(p.asset_id,p.asset_version_id);breadcrumbs([['案件',`/projects/${p.project_id}`],['制作物',`/assets/${p.asset_id}`],[`Version ${p.version}`,back],['証跡詳細']]);main.append(link(`← Version ${p.version} に戻る`,back));}await proofCard(p);bitcoinProofCard(p);const actions=el('div',undefined,'history-actions');main.append(actions);if(m[1]==='verify'&&p.verification?.has_ots)actions.append(link('OpenTimestamps証明ファイルをダウンロード',`/api/verify/${p.id}/ots`));if(m[1]==='proof'){if(!m[3])actions.append(link('ファイルと証跡を確認する',`/proof/${p.id}/check`));else actions.append(link('← 証跡詳細に戻る',`/proof/${p.id}`));if(p.verification?.has_ots)actions.append(link('OpenTimestamps証明ファイルをダウンロード',`/api/proofs/${p.id}/ots`));else main.append(el('p','証跡ファイルはまだ作成されていません。'));const membership=loginSession?.memberships?.find((member:Row)=>member.project_id===p.project_id);proofControls(p,actions,membership?.role);if(p.is_public){const url=new URL(`/verify/${p.id}`,location.origin).href;actions.append(link('公開Verifyを開く',url));}else main.append(el('p','この確認画面は案件メンバー専用です。公開対象として設定された自分の音楽作品だけに公開Verifyを表示します。','muted'));}return;}
 main.append(el('h1','ページが見つかりません'),link('トップへ','/'));
}
async function start(){loginSession=await api('/api/auth/session');showLoginUser();await render();}start().catch(error);

void adminNavigation().catch(()=>{});
